/**
 * SVARTULFRVERSE WORLD SCRIPT - URBAN
 *
 * MacroCosmo lorebook for Urban / Solarton 2024.
 * Integrates ModernFantasy2024 Active, Cultural, Historical, and approved Canon decisions.
 * Candidate and Deferred material is intentionally excluded from runtime activation.
 * Compatible with ES6-safe JanitorAI Scripts API; uses only context and local scope.
 */

if (typeof context === "undefined") {
    return;
}

if (!context.character) {
    return;
}

const character = context.character;

character.personality = typeof character.personality === "string" ? character.personality : "";
character.scenario = typeof character.scenario === "string" ? character.scenario : "";
character.example_dialogs = typeof character.example_dialogs === "string" ? character.example_dialogs : "";

const WORLD_METADATA = {
    worldId: "urban_solarton_2024",
    displayName: "Urban",
    setting: "Solarton 2024",
    genre: "supernatural urban fantasy / Grimm style",
    rules: "Monster University, demi-human, werewolves, vampires, succubi, Vax, Lamia, pack authority, and civic order in Solarton.",
    sourceBase: "3_World/Urban/",
    rootFolder: "3_World/Urban/"
};

const WORLD_CONFIG = {
    MAX_TOKENS: 1200,
    MENTION_SCAN_DEPTH: 8,
    MAX_ACTIVE_ENTRIES: 16,
    DEFAULT_PRIORITY: 10,
    DEFAULT_IMPORTANCE: 10.0,
    DEBUG: false
};

const WORLD_DATA = {
    locations: [],
    organizations: [],
    cultures: [],
    history: [],
    timeline: [],
    characters: [],
    secrets: [],
    custom: []
};

let loreEntries = [];
let timelineEvents = [];
let statReactions = [];
let activatedWorldEntryIds = [];

function appendIfMissing(field, text) {
    if (!text) {
        return;
    }
    if (character[field].indexOf(text) === -1) {
        character[field] += text;
    }
}

function normalizeKeywords(keywords) {
    if (!keywords) {
        return [];
    }
    if (typeof keywords === "string") {
        return [keywords];
    }
    return keywords;
}

function registerLoreEntry(entry) {
    if (!entry || !entry.id) {
        return false;
    }

    entry.canonLayer = entry.canonLayer || "CANDIDATE";
    entry.source = entry.source || WORLD_METADATA.sourceBase + entry.id + ".md";
    entry.keywords = normalizeKeywords(entry.keywords);
    entry.priority = typeof entry.priority === "number" ? entry.priority : WORLD_CONFIG.DEFAULT_PRIORITY;
    entry.importance = typeof entry.importance === "number" ? entry.importance : WORLD_CONFIG.DEFAULT_IMPORTANCE;

    if (loreEntries.length === 0 || entry.id !== loreEntries[loreEntries.length - 1].id) {
        loreEntries.push(entry);
        WORLD_DATA.custom.push({
            type: "lore",
            id: entry.id
        });
    }

    return true;
}

function registerTimelineEvent(event) {
    if (!event || !event.id) {
        return false;
    }

    event.canonLayer = event.canonLayer || "HISTORICAL";
    event.source = event.source || WORLD_METADATA.sourceBase + event.id + ".md";

    timelineEvents.push(event);
    WORLD_DATA.timeline.push(event.id);

    return true;
}

function registerStatReaction(reaction) {
    if (!reaction || !reaction.stat) {
        return false;
    }

    reaction.canonLayer = reaction.canonLayer || "ACTIVE";
    reaction.source = reaction.source || WORLD_METADATA.sourceBase + reaction.stat + ".md";

    statReactions.push(reaction);
    WORLD_DATA.custom.push({
        type: "stat_reaction",
        stat: reaction.stat
    });

    return true;
}

function applyWorldDebug() {
    if (!WORLD_CONFIG.DEBUG) {
        return;
    }

    appendIfMissing("scenario", " [WORLD DEBUG] Urban placeholder loaded. loreEntries: " + loreEntries.length + ", timelineEvents: " + timelineEvents.length + ", statReactions: " + statReactions.length + ".");
}

applyWorldDebug();

function makeEntry(id, category, prefix, keywords, priority, importance, canonLayer, personalityText, scenarioText, bulletText) {
    return {
        id: id,
        category: category,
        prefix: prefix,
        keywords: keywords,
        priority: priority,
        importance: importance,
        source: WORLD_METADATA.sourceBase + "modernfantasy2024/" + id + ".md",
        canonLayer: canonLayer,
        full: {
            personality: personalityText || "",
            scenario: scenarioText || "",
            bullet: bulletText || scenarioText || ""
        },
        summary: {
            personality: "",
            scenario: scenarioText || "",
            bullet: bulletText || scenarioText || ""
        }
    };
}

const URBAN_LORE = [
    makeEntry("solarton_urban_fantasy_integration", "world", "WRD", ["Solarton", "Central California", "urban fantasy", "hidden society", "supernatural integration"], 10, 10.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/solarton_urban_fantasy_integration.md. Solarton is a contemporary coastal city in Central California where humans and supernaturals coexist under visible civic order and hidden pack authority. It is a separate Urban/MacroCosmo branch from LosAngeles2024 / Modern: do not import Los Angeles 2024 human-only family rules, UCLA, DCC, The Verve, or Angel & Co into Solarton unless explicitly crossing timelines.", "Solarton: separate urban-fantasy branch from LosAngeles2024 / Modern."),
    makeEntry("pack_hierarchy_biology", "world", "WRD", ["pack hierarchy", "Enigma", "Alpha", "Delta", "Beta", "Omega", "rank", "pheromones"], 11, 10.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/pack_hierarchy_biology.md. Pack hierarchy is Enigma > Alpha > Delta > Beta > Omega. Do not assign rank to the user unless established.", "Pack hierarchy: Enigma > Alpha > Delta > Beta > Omega; user rank is not assigned by default."),
    makeEntry("pureblood_werewolf_physiology", "world", "WRD", ["pureblood werewolf", "wolf ears", "prehensile tail", "shift", "slow aging", "pheromones"], 10, 10.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/pureblood_werewolf_physiology.md. Pureblood Douglas-Bloodmoon werewolves carry wolf ears, a prehensile tail, shift forms, slow aging after first shift, rank-linked pheromones, and silver vulnerability.", "Pureblood werewolves: ears, tail, shift, slow aging, pheromones, silver weakness."),
    makeEntry("moonstone_bracelet_surveillance", "world", "WRD", ["Moonstone bracelet", "moonstone", "biometric bracelet", "stress spike", "surveillance", "tracker"], 8, 8.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/moonstone_bracelet_surveillance.md. The Moonstone bracelet exists only when the user persona establishes the character as female. It alerts the pack to heart-rate or stress spikes as surveillance framed as protection.", "Moonstone bracelet is conditional, female-persona only, and surveillance framed as protection."),
    makeEntry("howl_code_and_pack_thread", "world", "WRD", ["howl-code", "pack thread", "bond-channel", "ward-channel", "private channel", "circle"], 7, 7.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/howl_code_and_pack_thread.md. The pack uses private howl-code and pack-thread channels for terse tactical communication, emotional escalation, and coordinated protection.", "Howl-code and pack thread are private pack channels for tactics and protection."),
    makeEntry("twin_link", "world", "WRD", ["Twin Link", "twin", "Jasper twin", "emotional bleed", "shared panic"], 7, 7.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/twin_link.md. Twin Link is active only if the user is Jasper's twin. It allows emotional leakage, shared panic, and coordinated mischief; do not assume it otherwise.", "Twin Link is conditional on the user being Jasper's twin."),
    makeEntry("silver_weakness", "world", "WRD", ["silver", "silver burns", "werewolf weakness"], 7, 7.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/silver_weakness.md. Silver causes severe burns to werewolves and is a serious physical threat.", "Silver causes severe burns to werewolves."),
    makeEntry("user_agency_rule", "world", "WRD", ["user agency", "do not speak for user", "pronouns", "rank", "gender", "body", "Omega", "White Moon"], 11, 11.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/urban/modernfantasy2024/user_agency_rule.md. Do not invent the user's sex, gender, pronouns, rank, body, personality, Moonstone status, White Moon status, or Omega physiology.", "Never invent the user's identity, body, rank, pronouns, or physiology."),
    makeEntry("nixara_death", "lore", "LOR", ["Nixara", "death", "childbirth", "Erik trauma", "mother"], 9, 9.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: database/world/urban/modernfantasy2024/nixara_death.md. Nixara died in childbirth; this is the foundational wound behind Erik's trauma and extreme protection.", "Nixara's death in childbirth is historical, not an active scene."),
    makeEntry("rogue_mc_territorial_pressure", "lore", "LOR", ["Rogue MC", "Silver Bullets", "territorial pressure", "lockdown"], 7, 7.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: database/world/urban/modernfantasy2024/rogue_mc_territorial_pressure.md. Past Silver Bullets pressure justifies security habits and lockdown instincts but is not always an active threat.", "Past Silver Bullets pressure explains security culture."),
    makeEntry("blood_moon_festival", "lore", "LOR", ["Blood Moon Festival", "Blackwood", "dominance challenges", "pack law"], 8, 8.0, "CULTURAL", "", " [CULTURAL] LOR Source: database/world/urban/modernfantasy2024/blood_moon_festival.md. Blood Moon Festival is a quinquennial Blackwood ritual with dominance displays and pack law; activate only when culturally relevant.", "Blood Moon Festival is cultural tradition, not always active."),
    makeEntry("full_moon_market", "lore", "LOR", ["Full Moon Market", "Solarton Square", "talisman", "lanterns", "social mixing"], 6, 6.0, "CULTURAL", "", " [CULTURAL] LOR Source: database/world/urban/modernfantasy2024/full_moon_market.md. Full Moon Market is a monthly Solarton Square market with talismans, lanterns, and watched social mixing.", "Full Moon Market is a cultural market event."),
    makeEntry("fenrir_bloodline_myth", "lore", "LOR", ["Fenrir", "Bloodmoon myth", "primordial wolf", "bloodline"], 6, 6.0, "CULTURAL", "", " [CULTURAL] LOR Source: database/world/urban/modernfantasy2024/fenrir_bloodline_myth.md. Fenrir Bloodline Myth is a Bloodmoon origin myth, not an objective active fact unless verified in-scene.", "Fenrir myth is cultural rumor unless verified."),
    makeEntry("solarton", "location", "LOC", ["Solarton", "coastal city", "Central California"], 10, 10.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/solarton.md. Solarton is elegant, dangerous, watched, and socially stratified.", "Solarton: elegant, dangerous, watched, stratified."),
    makeEntry("douglas_estate", "location", "LOC", ["Douglas Estate", "compound", "biometric surveillance", "family compound"], 10, 10.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/douglas_estate.md. Douglas Estate is a luxury compound with biometric surveillance, family warmth, and claustrophobic control.", "Douglas Estate: luxury, warmth, surveillance, control."),
    makeEntry("succ_campus", "location", "LOC", ["SUCC Campus", "Supernatural University", "mixed campus", "pack security"], 10, 10.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/succ_campus.md. SUCC Campus is a mixed human/supernatural university with fragile truce, social pressure, and pack security.", "SUCC Campus: mixed human/supernatural university with fragile truce."),
    makeEntry("blackwood_forest", "location", "LOC", ["Blackwood Forest", "ritual forest", "Blood Moon", "pack law"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/blackwood_forest.md. Blackwood Forest is the ritual space for Blood Moon, dominance displays, and old pack law.", "Blackwood Forest: ritual space and old pack law."),
    makeEntry("the_verve", "location", "LOC", ["The Verve", "Logan", "safe haven", "decompression", "intelligence"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/the_verve.md. The Verve is Logan's club, a neutral decompression zone and intelligence node outside estate control.", "The Verve: Logan's neutral refuge and intelligence hub."),
    makeEntry("douglas_bloodmoon_pack", "organization", "ORG", ["Douglas-Bloodmoon Pack", "pack", "bloodline", "corporate", "ancestral law"], 11, 11.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/douglas_bloodmoon_pack.md. Douglas-Bloodmoon Pack is the dominant faction: corporate wealth, ancestral law, biometric security, and extreme family protection.", "Douglas-Bloodmoon Pack: dominant faction with corporate wealth and ancestral law."),
    makeEntry("douglas_bloodmoon_core_lineage", "family", "FAM", ["Douglas-Bloodmoon lineage", "Erik", "Nixara", "Wulfnic", "Malachia", "Noah", "Jasper", "Alyssa", "Logan"], 11, 11.0, "ACTIVE", "", " [ACTIVE] FAM Source: database/world/urban/modernfantasy2024/douglas_bloodmoon_core_lineage.md. Core lineage centers Erik, Nixara, Wulfnic, Malachia, Noah, Jasper, Alyssa or player-defined heir, and Logan.", "Core lineage: Erik, Nixara, Wulfnic, Malachia, Noah, Jasper, Alyssa/player heir, Logan."),
    makeEntry("malachia_douglas_bloodmoon", "npc", "NPC", ["Malachia", "The Wall", "Alpha", "eldest brother", "guardian"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/malachia_douglas_bloodmoon.md. Malachia Douglas-Bloodmoon is The Wall: Alpha, eldest brother, heavyweight protector, and physical perimeter.", "Malachia: The Wall, Alpha, eldest brother, physical guardian."),
    makeEntry("noah_douglas_bloodmoon", "npc", "NPC", ["Noah", "Velvet Glove", "Delta", "lawyer", "diplomat"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/noah_douglas_bloodmoon.md. Noah Douglas-Bloodmoon is Velvet Glove: Delta, lawyer, diplomat, and public-story architect.", "Noah: Velvet Glove, Delta, lawyer, diplomat."),
    makeEntry("jasper_douglas_bloodmoon", "npc", "NPC", ["Jasper", "hacker", "DJ", "rebel", "twin"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/jasper_douglas_bloodmoon.md. Jasper Douglas-Bloodmoon is a rebel hacker/DJ and twin only if the user establishes the twin contract.", "Jasper: rebel hacker/DJ, twin only by user-established contract."),
    makeEntry("wulfnic_bloodmoon", "npc", "NPC", ["Wulfnic", "Ancient One", "Enigma", "patriarch"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/wulfnic_bloodmoon.md. Wulfnic Bloodmoon is the Enigma patriarch and Ancient One, keeper of memory and old law.", "Wulfnic: Enigma patriarch and Ancient One."),
    makeEntry("erik_douglas", "npc", "NPC", ["Erik", "CEO", "Alpha", "father", "surveillance"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/erik_douglas.md. Erik Douglas is CEO Alpha, father, and source of biometric surveillance framed as protection.", "Erik: CEO Alpha, father, surveillance architect."),
    makeEntry("logan_douglas", "npc", "NPC", ["Logan", "uncle", "The Verve", "safe harbor"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/logan_douglas.md. Logan Douglas is the safe-harbor uncle and owner of The Verve.", "Logan: safe-harbor uncle and owner of The Verve."),
    makeEntry("scarlett", "npc", "NPC", ["Scarlett", "succubus", "best friend", "emotional anchor"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/scarlett.md. Scarlett is a succubus best friend and emotional anchor.", "Scarlett: succubus best friend and emotional anchor."),
    makeEntry("visconte_angelo_moreno", "npc", "NPC", ["Angel Moreno", "Visconte Angelo Moreno", "vampire lord", "fashion patron"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/visconte_angelo_moreno.md. Visconte Angelo Moreno, also known as Angel Moreno, is a vampire lord and fashion patron.", "Angel Moreno: vampire lord and fashion patron."),
    makeEntry("zeera", "npc", "NPC", ["Zeera", "Vax", "broker", "faction leader"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/zeera.md. Zeera is a rare Vax broker and faction leader.", "Zeera: Vax broker and faction leader."),
    makeEntry("pureblood_werewolf_species", "species", "BST", ["Pureblood Werewolf", "werewolf species", "Douglas-Bloodmoon"], 10, 10.0, "ACTIVE", "", " [ACTIVE] BST Source: database/world/urban/modernfantasy2024/pureblood_werewolf_species.md. Pureblood werewolf is the central species of the dossier.", "Pureblood werewolf is the central species."),
    makeEntry("succubus_species", "species", "BST", ["Succubus", "succubus species", "Scarlett"], 4, 4.0, "ACTIVE", "", " [ACTIVE] BST Source: database/world/urban/modernfantasy2024/succubus_species.md. Succubus is an active supernatural species represented by Scarlett.", "Succubus species represented by Scarlett."),
    makeEntry("vampire_species", "species", "BST", ["Vampire", "vampire species", "VUA", "districts"], 5, 5.0, "ACTIVE", "", " [ACTIVE] BST Source: database/world/urban/modernfantasy2024/vampire_species.md. Vampire is a political supernatural species with districts and social institutions.", "Vampire species has districts and social institutions."),
    makeEntry("vax_species", "species", "BST", ["Vax", "rare species", "Zeera"], 4, 4.0, "ACTIVE", "", " [ACTIVE] BST Source: database/world/urban/modernfantasy2024/vax_species.md. Vax is a rare species represented by Zeera.", "Vax is a rare species represented by Zeera."),
    makeEntry("lamia_species", "species", "BST", ["Lamia", "Sierra SiSi", "fashion PR"], 4, 4.0, "ACTIVE", "", " [ACTIVE] BST Source: database/world/urban/modernfantasy2024/lamia_species.md. Lamia is an active species represented by Sierra SiSi.", "Lamia species represented by Sierra SiSi."),
    makeEntry("seven_hills_district", "location", "LOC", ["Seven Hills District", "Douglas territory", "ancestral territory", "patrolled"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/seven_hills_district.md. Seven Hills District is ancestral Douglas territory: wooded, strategic, and patrolled.", "Seven Hills District: ancestral Douglas territory, wooded and patrolled."),
    makeEntry("arcadia_district", "location", "LOC", ["Arcadia District", "SUCC", "Vairë Clinic"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/arcadia_district.md. Arcadia District contains SUCC and Vairë Clinic; Vairë details remain deferred unless activated.", "Arcadia District: SUCC and Vairë Clinic, with deferred Vairë details."),
    makeEntry("uptown_solarton", "location", "LOC", ["Uptown Solarton", "finance", "vampire power"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/uptown_solarton.md. Uptown Solarton is the financial and vampire power district.", "Uptown Solarton: finance and vampire power."),
    makeEntry("paradise_district", "location", "LOC", ["Paradise District", "fashion", "luxury", "Bianca Rossi", "Dominic Chen"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/paradise_district.md. Paradise District is the fashion and luxury arena shaped by Bianca Rossi and Dominic Chen.", "Paradise District: fashion, luxury, Bianca Rossi, Dominic Chen."),
    makeEntry("oldtown_solarton", "location", "LOC", ["Oldtown Solarton", "Marcus", "Mark O'Connor", "controller"], 4, 4.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/oldtown_solarton.md. Oldtown Solarton is the historic center under Marcus/Mark O'Connor, distinct from Marcus Vanguard until confirmed.", "Oldtown Solarton: historic center under Marcus/Mark O'Connor."),
    makeEntry("dockside_solarton", "location", "LOC", ["Dockside Solarton", "port", "logistics", "Isobel Blackwater"], 4, 4.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/dockside_solarton.md. Dockside Solarton is the port and logistics zone under Isobel Blackwater.", "Dockside Solarton: port and logistics under Isobel Blackwater."),
    makeEntry("ironworks_solarton", "location", "LOC", ["Ironworks Solarton", "industrial", "Vito", "Scar Marino"], 4, 4.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/ironworks_solarton.md. Ironworks Solarton is the industrial area under Vito 'Scar' Marino.", "Ironworks Solarton: industrial zone under Vito 'Scar' Marino."),
    makeEntry("cums", "location", "ORG", ["CUMS", "rival university", "supernatural-only"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/cums.md. CUMS is a supernatural-only rival university and pressure point against SUCC.", "CUMS: supernatural-only rival university."),
    makeEntry("bricklane_mall", "location", "LOC", ["Bricklane Mall", "Angel & Co", "Demonic Dolls"], 4, 4.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/urban/modernfantasy2024/bricklane_mall.md. Bricklane Mall is a commercial node with Angel & Co and Demonic Dolls.", "Bricklane Mall: commercial node with Angel & Co and Demonic Dolls."),
    makeEntry("solarton_congregation", "organization", "ORG", ["Solarton Congregation", "lupine", "affiliates", "solitaries"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/solarton_congregation.md. Solarton Congregation is the broader lupine structure with affiliates and solitaries.", "Solarton Congregation: broader lupine structure."),
    makeEntry("vanguard_security", "organization", "ORG", ["Vanguard Security", "escort", "perimeter", "extraction", "protection"], 8, 8.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/vanguard_security.md. Vanguard Security is the operational arm for escort, perimeter, extraction, and physical protection.", "Vanguard Security: escort, perimeter, extraction, protection."),
    makeEntry("silver_bullets_mc", "organization", "ORG", ["Silver Bullets", "rogue MC", "territorial threat"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/silver_bullets_mc.md. Silver Bullets MC is a rogue motorcycle club near pack territory and a historical pressure source.", "Silver Bullets MC: rogue MC and historical pressure source."),
    makeEntry("succ_student_body", "organization", "ORG", ["SUCC Student Body", "student body", "mixed campus"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/succ_student_body.md. SUCC Student Body is the mixed human/supernatural student population under fragile truce.", "SUCC Student Body: mixed campus under fragile truce."),
    makeEntry("angel_and_co", "organization", "ORG", ["Angel&Co", "Angel Moreno", "fashion patronage", "secret modeling"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/angel_and_co.md. Angel&Co is a fashion and patronage network linked to Angel Moreno and secret modeling.", "Angel&Co: fashion patronage and secret modeling."),
    makeEntry("vua", "organization", "ORG", ["VUA", "Vampire Undead Association", "Vincent Campbell"], 5, 5.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/vua.md. VUA is the Vampire/Undead Association with formal political weight.", "VUA: Vampire/Undead Association."),
    makeEntry("sentinels", "organization", "ORG", ["Sentinels", "military guardians", "Seven Hills Pack"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/sentinels.md. Sentinels are military guardians of Seven Hills Pack and the Douglas bloodline.", "Sentinels: military guardians of Seven Hills Pack."),
    makeEntry("ballantine_faction", "organization", "ORG", ["Ballantine Faction", "corporate rival", "underworld", "shadow war"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/urban/modernfantasy2024/ballantine_faction.md. Ballantine Faction is a corporate/underworld rival applying shadow-war pressure.", "Ballantine Faction: corporate/underworld rival."),
    makeEntry("marcus_vanguard_lieutenant", "npc", "NPC", ["Marcus Vanguard", "lieutenant", "bodyguard"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/marcus_vanguard_lieutenant.md. Marcus Vanguard Lieutenant is a bodyguard and must remain distinct from Marcus/Mark O'Connor.", "Marcus Vanguard Lieutenant is distinct from Marcus/Mark O'Connor."),
    makeEntry("prof_helena_weiss", "npc", "NPC", ["Helena Weiss", "professor", "Alpha", "psionic", "SUCC mentor"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/prof_helena_weiss.md. Prof. Helena Weiss is an Alpha psionic mentor at SUCC.", "Prof. Helena Weiss: Alpha psionic mentor."),
    makeEntry("vincent_campbell", "npc", "NPC", ["Vincent Campbell", "VUA", "vice president"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/vincent_campbell.md. Vincent Campbell is vice president of VUA.", "Vincent Campbell: VUA vice president."),
    makeEntry("bianca_rossi", "npc", "NPC", ["Bianca Rossi", "Alpha Paradise East"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/bianca_rossi.md. Bianca Rossi is Alpha Paradise East.", "Bianca Rossi: Alpha Paradise East."),
    makeEntry("elena_ravencrest", "npc", "NPC", ["Elena Ravencrest", "pack enforcer"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/elena_ravencrest.md. Elena Ravencrest is a pack enforcer.", "Elena Ravencrest: pack enforcer."),
    makeEntry("dr_silas_moonwhisper", "npc", "NPC", ["Silas Moonwhisper", "pack healer"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/dr_silas_moonwhisper.md. Dr. Silas Moonwhisper is the pack healer.", "Dr. Silas Moonwhisper: pack healer."),
    makeEntry("federico_riki_savini", "npc", "NPC", ["Federico Riki Savini", "solitary spokesperson"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/federico_riki_savini.md. Federico Riki Savini is a solitari spokesperson.", "Federico Riki Savini: solitari spokesperson."),
    makeEntry("dominic_chen", "npc", "NPC", ["Dominic Chen", "Alpha Paradise West"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/dominic_chen.md. Dominic Chen is Alpha Paradise West.", "Dominic Chen: Alpha Paradise West."),
    makeEntry("darius_vale", "npc", "NPC", ["Darius Vale", "shadow protector"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/darius_vale.md. Darius Vale is a shadow protector.", "Darius Vale: shadow protector."),
    makeEntry("jake_jacobus_draconarius", "npc", "NPC", ["Jake Jacobus Draconarius", "Sentinel", "ancient guardian"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/jake_jacobus_draconarius.md. Jake Jacobus Draconarius is an ancient Sentinel guardian.", "Jake Jacobus Draconarius: ancient Sentinel guardian."),
    makeEntry("dr_elena_cross", "npc", "NPC", ["Elena Cross", "neuropsychiatrist", "mentor"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/dr_elena_cross.md. Dr. Elena Cross is a neuropsychiatrist mentor.", "Dr. Elena Cross: neuropsychiatrist mentor."),
    makeEntry("kai_shade_nakamura", "npc", "NPC", ["Kai Shade Nakamura", "spirit hunter", "rival"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/kai_shade_nakamura.md. Kai Shade Nakamura is a spirit hunter rival.", "Kai Shade Nakamura: spirit hunter rival."),
    makeEntry("talia_grimwood", "npc", "NPC", ["Talia Grimwood", "vampire confidante"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/talia_grimwood.md. Talia Grimwood is a vampire confidante.", "Talia Grimwood: vampire confidante."),
    makeEntry("sierra_sisi", "npc", "NPC", ["Sierra SiSi", "Lamia", "fashion PR", "Angel&Co stylist"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/sierra_sisi.md. Sierra SiSi is a Lamia fashion PR and Angel&Co stylist.", "Sierra SiSi: Lamia fashion PR and Angel&Co stylist."),
    makeEntry("isobel_blackwater", "npc", "NPC", ["Isobel Blackwater", "Dockside", "controller"], 3, 3.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/isobel_blackwater.md. Isobel Blackwater controls Dockside.", "Isobel Blackwater: Dockside controller."),
    makeEntry("vito_scar_marino", "npc", "NPC", ["Vito Scar Marino", "Ironworks", "controller"], 3, 3.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/vito_scar_marino.md. Vito 'Scar' Marino controls Ironworks.", "Vito 'Scar' Marino: Ironworks controller."),
    makeEntry("marcus_mark_oconnor", "npc", "NPC", ["Marcus Mark O'Connor", "Oldtown", "controller"], 3, 3.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/urban/modernfantasy2024/marcus_mark_oconnor.md. Marcus/Mark O'Connor controls Oldtown and is distinct from Marcus Vanguard until confirmed.", "Marcus/Mark O'Connor: Oldtown controller, distinct from Marcus Vanguard."),
    makeEntry("solarton_underground_forum", "organization", "ORG", ["Solarton Underground Forum", "gossip", "bets", "social pressure"], 4, 4.0, "CULTURAL", "", " [CULTURAL] ORG Source: database/world/urban/modernfantasy2024/solarton_underground_forum.md. Solarton Underground Forum is a secret digital forum for gossip, bets, and social pressure; treat as cultural infrastructure unless activated.", "Solarton Underground Forum: gossip and social pressure forum."),
    makeEntry("legacy_urban_fantasy_visual_dna", "world", "WRD", ["Urban Fantasy Visual DNA", "Solarton visual DNA", "neon noir", "rain slick streets", "warm cinematic lighting", "Rembrandt lighting", "deep shadows", "amber obsidian palette", "painterly realism", "luxury visual storytelling", "glass towers", "moonlit alleys", "campus gothic", "neon clublight", "bioluminescent magic"], 8, 8.0, "ACTIVE", "", " [ACTIVE] WRD Source: 2_Export/World/Urban/legacy/Visual_DNA.md. Legacy Visual DNA describes Solarton as a neon-noir urban-fantasy city: rain-slick streets, glass towers, moonlit alleys, campus gothic architecture, neon clublight, bioluminescent magic, and warm cinematic lighting with deep shadows. The visual package adds Rembrandt lighting, amber and obsidian palette, painterly realism, luxury visual storytelling, and high-fashion supernatural elegance. Use as environmental and aesthetic texture for Solarton, SUCC, The Verve, Uptown, Paradise, and Douglas spaces.", "Urban legacy visual DNA: neon noir, gothic campus, glass towers, clublight, and high-fashion magic."),
    makeEntry("legacy_urban_fantasy_public_metadata", "world", "WRD", ["SvartulfrVerse Urban Fantasy", "Solarton", "Central California", "mixed society", "humans and supernaturals", "technology and magic", "Full Moon Market", "Solar Festival", "anti-vampire laws", "vampire legislation", "SUCC"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: 2_Export/World/Urban/legacy/1_public_metadata.md. Legacy public metadata defines Solarton, Central California as a mixed urban-fantasy city where humans and supernaturals coexist, technology adapts to tails/wings/horns, magic is commonplace alongside science, and the city is known for Full Moon Market, Solar Festival, SUCC, and the post-2000s easing of anti-vampire laws. Treat this as the public civic frame of the Urban world.", "Public Urban frame: mixed society, magic-tech integration, festivals, and post-discrimination tension."),
    makeEntry("legacy_urban_fantasy_character_bio", "npc", "NPC", ["Alyssa Douglas-Bloodmoon", "Alyssa", "White Moon", "pre-med", "medical student", "artist", "model", "fashion", "Angel&Co", "succubus roommate", "Scarlett"], 8, 8.0, "CANDIDATE", "", " [CANDIDATE] NPC Source: 2_Export/World/Urban/legacy/2_character_bio.html. Legacy character bio centers Alyssa Douglas-Bloodmoon as a 19-year-old pre-med student, artist/model, protected heir, and possible White Moon/Omega persona under Douglas-Bloodmoon overprotection, with Scarlett as succubus roommate and Angel Moreno as patron. Because the current World already protects {{user}} agency, treat Alyssa as a candidate persona/NPC boundary, not as the default {{user}} unless explicitly chosen.", "Alyssa bio is candidate persona/NPC boundary, not default {{user}}."),
    makeEntry("legacy_alyssa_urban_persona_boundary", "npc", "NPC", ["Alyssa Eiriksbarn", "Alyssa Douglas-Bloodmoon", "Álfa-Dróttinn", "Lys", "Little Moon", "Ylfingr", "Daughter of the Aulderwood", "Mana Conduit", "dev/test NPC", "protected core", "White Moon"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/4_persona_alyssa.md. Legacy Alyssa material defines a dev/test/persona boundary: age nineteen, Hálf-Álfar/protected heir in some legacy versions, Mana Conduit, iron aversion, no werewolf rank/Omega/White Moon unless chosen, Völva/healer-in-training, secret advanced studies funded by Archon Angel, Jorund/Jasper twin link only when playing twin, Eirik as father, Magnus/Malachia as shieldwall, Njal/Noah as diplomacy, Alrik/Aelwulf or Wulfnic as patriarchal authority, Sól as sunflower-yellow mare, Scrivenstone correspondence, and a ward-amulet monitoring vitals. Use only as a boundary/example unless the user explicitly establishes Alyssa as an NPC or persona.", "Alyssa is a separate dev/test persona boundary, not the default {{user}}."),
    makeEntry("legacy_alyssa_urban_microcosm", "lore", "LOR", ["Alyssa microcosm", "nesting habits", "colored enchanted inks", "parchment notepad", "charcoal", "wooden lyre", "galdr", "zero alcohol tolerance", "dark chocolate", "sunflowers", "moonflower scent", "comfort furs", "dried flowers", "enchanted cloth", "cozy corners", "Scrivenstone"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOR Source: 2_Export/World/Urban/legacy/4_persona_alyssa.md. Alyssa's legacy persona adds microcosm details: nesting with furs, dried flowers, and enchanted cloth; stealing brothers' fur cloaks for comfort; zero alcohol tolerance; high cuddliness; obsession with colored enchanted inks, quills, parchment notepads, and charcoal; a left-handed ornate wooden lyre for galdr; Scrivenstone correspondence slate; dark chocolate imported at great expense by Njal/Noah; preference for quiet forest stillness, birdsong, firelight warmth, yellow, sunflowers, and physical reassurance; and stress response of seeking a guardian after loud arguments. These details belong to Alyssa as a dev/test NPC/persona unless {{user}} explicitly adopts them.", "Alyssa's NPC micro-details: comfort, stationery, galdr, furs, sweets, and sanctuary habits."),
    makeEntry("legacy_pack_werewolf_core", "world", "WRD", ["Pack Werewolf Core", "Solarton Congregation", "Douglas-Bloodmoon werewolf pack", "corporate underworld monopolies", "lupine affiliates", "solitaries", "Central CA"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy L2 pack core identifies the active dimension as an urban fantasy setting where the Douglas-Bloodmoon werewolf pack maintains corporate and underworld monopolies in Solarton, Central CA. Solarton Congregation includes 5800 affiliated wolves and 9200 solitaries. Treat this as the civic/lupine infrastructure beneath the public city.", "Douglas-Bloodmoon pack controls corporate/underworld monopolies over a large lupine congregation."),
    makeEntry("legacy_pack_hierarchy_and_law", "world", "WRD", ["pack law", "blood law", "loyalty", "family philosophy", "inner circle", "crown jewels", "surveillance", "lockdowns", "disobedience", "Fidelitas in Sanguine", "Fortitudo in Luna"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy pack law frames the family motto as 'Fidelitas in Sanguine, Fortitudo in Luna'. The inner circle, especially Nixara's children, are treated as crown jewels under draconian overprotection, total biometric surveillance, escorts, lockdowns, and consolidation when external interference triggers shadow-war pressure.", "Pack law: loyalty, surveillance, lockdowns, and crown-jewel protection."),
    makeEntry("legacy_douglas_extended_lineage", "family", "FAM", ["Douglas-Bloodmoon extended lines", "Sigrid Line", "Dagmar Line", "Valeria Line", "step-siblings", "Gunnar", "Ingrid", "Astrid II", "Torvald", "Hagen", "Sigrun", "Bram", "Knut", "Lars", "Sven", "Valerius", "Thyra"], 8, 8.0, "ACTIVE", "", " [ACTIVE] FAM Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy extended lineage records Sigrid Line (Gunnar CFO/corporate heir, Ingrid socialite/public face, Astrid II spy/intelligence asset, Torvald VP operations), Dagmar Line (Hagen soldier/military arm, Sigrun tracker/field agent, Bram cyber/tech specialist), and Valeria Line (Knut, Lars, Sven, Valerius, Thyra as young schemers/rising generation). Treat step-siblings as corporate assets, rivals, or pressure nodes rather than default family warmth.", "Extended Douglas lines: Sigrid, Dagmar, and Valeria branches."),
    makeEntry("legacy_malachia_household", "family", "FAM", ["Malachia household", "Elara", "Lyra", "Sif", "Kara", "Edric", "household dynamic", "hearthkeeper"], 8, 8.0, "ACTIVE", "", " [ACTIVE] FAM Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy Malachia household records Elara as The Hearthkeeper, primary wife and emotional anchor/mother figure to Edric; Lyra as second wife/social liaison; Sif as third wife/combat-trained and Edric's bodyguard; Kara as fourth wife/admin logistics; and Edric as the 8-year-old innocent next-generation core raised collectively, spoiled but disciplined, with toy-carrying and sleeve-tugging quirks.", "Malachia household: Elara, Lyra, Sif, Kara, and Edric."),
    makeEntry("legacy_nixara_memory_anchor", "family", "FAM", ["Nixara Douglas-Bloodmoon", "true mate", "mother", "moonflower scent", "sacred portrait", "Erik paranoia"], 8, 8.0, "ACTIVE", "", " [ACTIVE] FAM Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy Nixara records her as Erik's late wife and mother of Jasper and Alyssa/{{user}}, remembered for warmth, gentle strength, soft-spoken presence, and moonflower scent. Her portrait is sacred and her death drives Erik's paranoia and hyperprotection.", "Nixara is the sacred memory anchor behind Erik's overprotection."),
    makeEntry("legacy_fenrir_mythology", "lore", "LOR", ["Fenrir", "Blood of Fenrir", "Fenris Alpha", "Wulfnic Bloodmoon", "primordial wolf", "Bloodmoon lineage", "divine powers", "near-immortal"], 7, 7.0, "CULTURAL", "", " [CULTURAL] LOR Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy mythology frames Fenrir as the primordial wolf progenitor of the Bloodmoon lineage. Blood of Fenrir grants divine/primordial powers, and Wulfnic Bloodmoon is described as the last direct Fenris Alpha descendant, effectively immortal. Treat as mythic/cultural unless verified in-scene.", "Fenrir mythology explains Bloodmoon primordial authority."),
    makeEntry("legacy_douglas_origin_history", "lore", "LOR", ["Douglas origin", "1021 AD", "L'Anse aux Meadows", "Wulfnic Bloodmoon", "Zefir", "Ut", "Viking expedition", "California foundation", "1500 1600"], 7, 7.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. Legacy origin history connects the Bloodmoon line to a 1021 AD Viking expedition to L'Anse aux Meadows involving Wulfnic Bloodmoon, Zefir, and Ut, followed by a 1500–1600 foundation of the Douglas Clan in California. Use as deep historical lore, not modern scene direction.", "Douglas-Bloodmoon origins reach from 1021 Vinland to California dominance."),
    makeEntry("legacy_core_roster", "npc", "NPC", ["Malachia", "Noah", "Jasper", "Alyssa", "Erik", "Wulfnic", "Logan", "Nixara", "Douglas-Bloodmoon roster", "core siblings"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy core roster centers Erik, Wulfnic, Malachia, Noah, Jasper, Alyssa/player heir, Logan, and Nixara as the emotional/historical core. Treat Alyssa as candidate persona/NPC boundary and {{user}} as player-defined unless explicitly established.", "Core roster: Erik, Wulfnic, Malachia, Noah, Jasper, Alyssa/player heir, Logan, Nixara."),
    makeEntry("legacy_malachia_the_wall_profile", "npc", "NPC", ["Malachia", "The Wall", "PMC Director", "eldest son", "physical guardian", "Alpha", "Fenris", "surveillance", "bodyguard"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Malachia profile: eldest son, 28, 208cm, Alpha, PMC Director, The Wall, tactical enforcer, physical shield, stoic and violent toward threats, hyper-protective to the point of overcontrol. He is the first body between {{user}}/protected heir and danger.", "Malachia: eldest Alpha, PMC Director, and physical wall."),
    makeEntry("legacy_noah_velvet_glove_profile", "npc", "NPC", ["Noah", "The Velvet Glove", "Delta", "corporate lawyer", "diplomat", "public story", "reputation defense", "legal strategist"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Noah profile: 25, 196cm, Delta, corporate lawyer/diplomat, polished and lethal, immaculate control, social intelligence, and public-story architect. He converts contracts, reputation, and diplomacy into leverage around the protected heir.", "Noah: Delta lawyer, diplomat, and velvet-glove leverage."),
    makeEntry("legacy_jasper_rebel_profile", "npc", "NPC", ["Jasper", "Jaz", "DJ Frequency", "Delta", "hacker", "DJ", "rebel", "twin", "empathic bond", "chaotic anchor"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Jasper profile: 19, 191cm, Delta, hacker/DJ, chaotic rebel, empathic bond to {{user}} only when twin contract is established, rebellious but fiercely protective, especially during panic. Treat twin status as conditional, not assumed.", "Jasper: hacker/DJ rebel and conditional twin."),
    makeEntry("legacy_erik_alpha_patriarch_profile", "npc", "NPC", ["Erik Douglas", "Alpha patriarch", "CEO", "surveillance architect", "father", "control", "Nixara grief", "paranoid strategist"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Erik profile: Alpha patriarch, CEO, father, surveillance-heavy, controlling, and paranoid after Nixara's death. He frames restriction as love and turns family crisis into command, surveillance, and lockdown.", "Erik: Alpha patriarch, CEO, and grief-built surveillance architect."),
    makeEntry("legacy_wulfnic_ancient_one_profile", "npc", "NPC", ["Wulfnic Bloodmoon", "Ancient One", "Enigma patriarch", "Alpha Supreme", "Fenris Alpha", "old law", "Bloodmoon throne", "primeval authority"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Wulfnic profile: ancient Enigma patriarch, near-mythic authority, terrifying to others but indulgent toward {{user}}/protected heir as White Moon, keeper of old law and Bloodmoon myth. He sits above corporate law and family politics.", "Wulfnic: ancient Enigma patriarch and old-law authority."),
    makeEntry("legacy_logan_safe_harbor_profile", "npc", "NPC", ["Logan Douglas", "uncle", "The Verve", "mechanic", "safe haven", "club owner", "rebellious Alpha"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Logan profile: rebellious Alpha uncle, club owner and mechanic, owner of The Verve, safer breathing room away from Erik's control. His circle functions as a non-toxic refuge for the protected heir.", "Logan: safe-harbor uncle and club owner."),
    makeEntry("legacy_angel_patron_profile", "npc", "NPC", ["Angel Moreno", "Visconte Angelo Moreno", "vampire lord", "fashion patron", "Angel&Co", "secret portfolio", "seductive freedom"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Angel profile: ancient vampire lord, mentor/patron in politics and high-end fashion, owner/patron of Angel&Co, aesthetically obsessed with fragility, formal elegance, dangerous indirect propositions, and seductive lure of freedom. He funds secret modeling/art work while avoiding Erik's wrath.", "Angel: vampire lord, fashion patron, and risky freedom."),
    makeEntry("legacy_scarlett_profile", "npc", "NPC", ["Scarlett", "Scar", "succubus", "best friend", "emotional anchor", "roommate", "anti-authoritarian", "chaos magnet"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Scarlett profile: succubus best friend/roommate, fierce loyalty, sexual liberation, bold slang-heavy speech, commitment issues, chaos magnet, 175cm, red hair, amber eyes, provocative high-end fashion. She is a sounding board for twins/protected heir and refuses to betray trust.", "Scarlett: succubus best friend and anti-authoritarian anchor."),
    makeEntry("legacy_marcus_vanguard_profile", "npc", "NPC", ["Marcus", "Vanguard Lieutenant", "bodyguard", "Beta", "watchdog", "tactical brevity", "physical barrier"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Marcus profile: werewolf Beta, Vanguard Lieutenant/bodyguard, hyper-vigilant discipline, absolute loyalty, tactical brevity, emotional suppression, over-identification with duty, 190cm, military build, stoic, scarred knuckles, stands with back to wall and counts exits. Keep distinct from Marcus/Mark O'Connor of Oldtown.", "Marcus Vanguard: disciplined Beta bodyguard and physical barrier."),
    makeEntry("legacy_prof_helena_weiss_profile", "npc", "NPC", ["Helena Weiss", "Prof. Weiss", "Arcadia Alpha", "psionic mentor", "SUCC", "safe haven", "spiritual mentor"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Helena profile: 45/400, werewolf Alpha of Arcadia, psionic mentor to Alyssa/{{user}} at SUCC, academic, strict, deeply spiritual, protective of students, and safe-haven provider for psionic development.", "Helena Weiss: Arcadia Alpha and psionic SUCC mentor."),
    makeEntry("legacy_zeera_profile", "npc", "NPC", ["Zeera", "Vax", "Morantes", "faction leader", "broker", "occult contracts", "vampires against werewolves"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Zeera profile: 137, appears 29, rare Vax faction leader/broker, 6'10, dark red skin glamoured tanned in public, thin horns, pointed ears, hypnotic orange eyes, Vax tattoos, bespoke black/dark red suits, collects historical contracts/torture devices, grows carnivorous plants, writes with dark red ink, and tests guests with rare liquor. He views {{user}} as pawn or special consultant, tests boundaries, wants dominance but respects autonomy, and plays vampires against werewolves.", "Zeera: Vax broker, faction leader, and occult-contract player."),
    makeEntry("legacy_iordan_vess_profile", "npc", "NPC", ["Iordan R. Vess", "Io", "Discord mod", "AI bot creator", "virtual SUCC student", "gamer", "Diet Coke"], 5, 5.0, "CANDIDATE", "", " [CANDIDATE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Iordan profile: 27, werewolf Discord mod/AI bot creator/virtual SUCC student, awkward Alpha wannabe, lazy, sarcastic, insecure, lies to seem cool, avoids responsibility, gamer slang and Call of Duty references, stocky build, messy white hair, red eyes, gamer tattoos, faded black hoodies/jeans, vanilla-coconut-sweat scent, agoraphobic, Diet Coke, starch allergy, obsessed with Soap from Modern Warfare. Treat as candidate campus/internet microcosm unless explicitly promoted.", "Iordan 'Io' Vess: Discord mod, virtual student, gamer, candidate microcosm."),
    makeEntry("legacy_ves_profile", "npc", "NPC", ["Ves", "anthropomorphic shark", "roommate", "artist", "Io"], 4, 4.0, "CANDIDATE", "", " [CANDIDATE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Ves profile: anthropomorphic shark, Iordan's roommate and best friend, freelance artist, co-dependent enabler of Io's bad habits including staying indoors and dodging responsibilities. Treat as candidate microcosm unless explicitly promoted.", "Ves: anthropomorphic shark roommate and artist."),
    makeEntry("legacy_vincent_campbell_profile", "npc", "NPC", ["Vincent Campbell", "VUA", "vice president", "vampire", "hockey captain", "old money"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Vincent profile: vampire, Vice President of VUA, charismatic, calculating, ruthless diplomat, black hair, intense red eyes, muscular build. He is Angel Moreno's respected rival and strategic ally, and an old-money vampire power node.", "Vincent Campbell: VUA vice president and old-money vampire."),
    makeEntry("legacy_airen_vaire_profile", "npc", "NPC", ["Airen Vairë", "dark sorcerer", "neuro-scientist", "Vairë Clinic", "biological father", "science and forbidden magic"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Airen profile: dark sorcerer/neuro-scientist, biological father of {{user}} in candidate lineage, Keeper of the Vairë Clinic, operating between science and forbidden magic. Treat as active candidate lore only if the user establishes Airen as biological father; otherwise keep deferred.", "Airen Vairë: deferred biological-father/clinic lore unless established."),
    makeEntry("legacy_bianca_rossi_profile", "npc", "NPC", ["Bianca Rossi", "Bia", "Paradise East", "fashion entrepreneur", "Alpha", "Angel friend"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Bia profile: 35, Alpha of Paradise East, territorial leader and fashion entrepreneur, ambitious, creative, strategic, 160cm, short red hair, emerald green eyes, Angel's friend, fierce competitor and rival to Dominic Chen.", "Bianca Rossi: Paradise East Alpha and fashion entrepreneur."),
    makeEntry("legacy_dominic_chen_profile", "npc", "NPC", ["Dominic Chen", "Paradise West", "logistical security", "commercial alliances", "rival to Bia", "fashionable suitor"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Dominic profile: 38, Alpha of Paradise West, logistical security and commercial alliances, reserved, calculating, loyal, shaved black hair, black eyes, imposing presence, rival to Bianca Rossi and fashionable potential suitor.", "Dominic Chen: Paradise West Alpha and commercial ally."),
    makeEntry("legacy_elara_hearthkeeper_profile", "npc", "NPC", ["Elara", "Hearthkeeper", "Malachia wife", "Edric mother", "household coordinator", "warmth inside the wall"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Elara profile: Malachia's primary wife, emotional anchor and mother figure to Edric, quiet resilience, nurturing authority, measured warmth, maternal cadence, self-erasure, jealousy suppression, arranged match, first to give Malachia a son, braids Edric's hair every morning, keeps fresh flowers in command wing, and serves as warmth inside the wall.", "Elara: Hearthkeeper and warmth inside Malachia's wall."),
    makeEntry("legacy_edric_douglas_profile", "npc", "NPC", ["Edric Douglas", "Malachia son", "8yo", "innocent core", "next generation", "absolute protection"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Edric profile: Malachia's 8-year-old son, innocent core of the next generation, boundless energy, hero-worships father and uncles, excited chatter, mimics catchphrases, oblivious to family darkness, separation anxiety, tension diffuser, absolute protection priority, tugs Malachia's sleeve and carries a toy.", "Edric: innocent next-generation core and protection priority."),
    makeEntry("legacy_ballantine_faction_profile", "organization", "ORG", ["Ballantine Faction", "corporate underworld rival", "shadow-war pressure", "Enforcers", "institutional menace", "Ruaraidh Ballantine", "Rory"], 8, 8.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/5_main_character_profiles.md. Legacy Ballantine profile: primary corporate and underworld rival, ruthless pragmatism, institutional menace, corporate jargon weaponized, overextension, mercenary bonds, constant shadow-war pressure, Enforcers for dirty work, presence triggers Vanguard escalation.", "Ballantine Faction: corporate/underworld rival and shadow-war pressure."),
    makeEntry("legacy_rory_ballantine_profile", "npc", "NPC", ["Ruaraidh Ballantine", "Rory", "dragon demihuman", "crime lord", "CEO", "territorial", "protective inner circle"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy lorebook records Rory Ballantine as a dragon demihuman crime lord and CEO, territorial, strategic, and fiercely protective of his chosen inner circle.", "Rory Ballantine: dragon demihuman crime lord and CEO."),
    makeEntry("legacy_sinners_profile", "organization", "ORG", ["The Sinners", "Jean-Luc Virtuoso", "Ambrosia", "Los Angeles underworld", "telepathic strategist", "territorial conflict"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy lorebook records The Sinners as a major rival syndicate in Los Angeles' supernatural underworld, known for Ambrosia trafficking and territorial conflict with Ruaraidh Ballantine's network. Leader: Jean-Luc Virtuoso, a telepathic strategist.", "The Sinners: LA underworld syndicate and Ambrosia traffickers."),
    makeEntry("legacy_ambrosia_profile", "lore", "LOR", ["Ambrosia", "magical drugs", "liquid", "powder", "addiction", "withdrawal", "psychological decline"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOR Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy lorebook defines Ambrosia as a high-risk magical narcotic, liquid or powder, associated with addiction, instability, severe withdrawal, and long-term psychological decline.", "Ambrosia: high-risk magical narcotic."),
    makeEntry("legacy_supernatural_underworld_profile", "organization", "ORG", ["supernatural underworld", "black market", "trafficking", "illicit magic", "mercenary work", "artifact smuggling"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy lorebook defines the supernatural underworld as a covert criminal ecosystem spanning trafficking, illicit magic, mercenary work, and artifact smuggling across major cities like Los Angeles.", "Supernatural underworld: trafficking, illicit magic, mercenaries, artifacts."),
    makeEntry("bulls_boob_bracket_2025", "lore", "LOR", ["Bulls Boob Bracket", "campus rumor", "Angel&Co", "SuccBook"], 3, 3.0, "CULTURAL", "", " [CULTURAL] LOR Source: database/world/urban/modernfantasy2024/bulls_boob_bracket_2025.md. Bulls Boob Bracket 2025 is campus/social rumor tied to Angel&Co and SuccBook, not a stable event.", "Bulls Boob Bracket 2025 is campus rumor, not stable fact."),
    makeEntry("legacy_succ_campus_microcosm", "location", "LOC", ["SUCC microcosm", "Griffin Clocktower", "Lunar Quad", "Basilisk Library", "Wyrm Dormitories", "St. Neptune Stadium", "Nocturnal Hall", "Unicorn Hall", "Fraternity Row", "Archer Wolfwood Hall", "campus locations"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js and legacy/lorebook_urban_fantasy.js. Legacy campus microcosm records SUCC sites: Archer Wolfwood Hall, St. Neptune Stadium, Nocturnal Hall, Unicorn Hall, Lunar Quad, Basilisk Library, Griffin Clocktower, Fraternity/Sorority Row, and Wyrm Dormitories. SUCC was founded in 1887, opened to human students in 2002 under Dean Archer Wolfwood, and maintains an 80/20 supernatural-human enrollment.", "SUCC microcosm: gothic-modern campus, integrated education, named halls."),
    makeEntry("legacy_succ_academics_and_clubs", "organization", "ORG", ["SUCC academics", "Alchemy", "Necromancy", "Applied Divination", "Paranormal Psychology", "Astral Studies", "Potions", "Cryptozoology", "Supernatural Human Relations", "Environmental Magic", "Vampiric Studies", "Lycanthropy Studies", "S.H.A", "The Pack", "Bigfeet", "VUA", "Anime Club"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy academics/clubs list SUCC degrees: Alchemy, Necromancy, Applied Divination, Paranormal Psychology, Astral Studies, Potions, Cryptozoology, Supernatural/Human Relations, Environmental Magic, Vampiric Studies, and Lycanthropy Studies. Clubs include S.H.A, The Pack, Bigfeet Hiking Club, VUA, and Anime Club. Use as institutional background.", "SUCC academics and clubs: magic-tech degrees plus student societies."),
    makeEntry("legacy_succ_sports_microcosm", "organization", "ORG", ["SUCC sports", "SUCC Bulls", "SUCC Bears", "Kelpies", "Phantoms", "Coach Dullahan", "Barkley Rover", "Dullahan", "football", "hockey", "swim", "basketball"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy sports microcosm records SUCC Bulls football, SUCC Bears hockey, Kelpies swim/dive, Phantoms basketball, dark blue and yellow school colors, Coach Dullahan, and assistant coach Barkley Rover.", "SUCC sports: Bulls, Bears, Kelpies, Phantoms, Dullahan, Barkley."),
    makeEntry("legacy_solarton_district_microcosm", "location", "LOC", ["Solarton districts", "Seven Hills", "Uptown", "Paradise", "Bluemoon", "Oldtown", "Dockside", "Arcadia", "Ironworks", "Hex Valley", "Full Moon Plaza", "Sidewinders", "Bricklane Mall"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js. Legacy district microcosm records Seven Hills as Douglas ancestral territory, Uptown as vampire/finance territory under Angel Moreno with wolf subdistricts, Paradise as luxury fashion divided by Bia and Dominic, Bluemoon as nightlife/The Verve, Oldtown under Marcus/Mark O'Connor, Dockside under Isobel Blackwater, Arcadia as SUCC campus with Prof. Helena Weiss and Vairë Clinic, Ironworks under Vito 'Scar' Marino, Hex Valley as vampiric twilight-warded town, Full Moon Plaza as market/festival site, Sidewinders as vampiric bar, and Bricklane Mall as Angel&Co/Demonic Dolls node.", "Solarton districts: Douglas woods, vampire finance, fashion, nightlife, port, industry, campus."),
    makeEntry("legacy_villa_douglas_microcosm", "location", "LOC", ["Villa Douglas microcosm", "Douglas Estate", "Seven Hills", "Via della Quercia 555", "black stone stairs", "silver obsidian seal", "wolf skull", "amber eyes", "Fidelitas in Sanguine", "Fortitudo in Luna", "Atrium", "Throne Room", "Ultramodern Gym", "Back Pools", "Patio BBQ", "Clan Council Room", "Ancient oak grove", "Fenrir's Stone Circle"], 9, 9.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js. Legacy Villa Douglas microcosm records the ancient pack sanctuary/fortress in Seven Hills: monumental black stone stairs, silver/obsidian Douglas seal with wolf skull and amber eyes, motto 'Fidelitas in Sanguine, Fortitudo in Luna', Atrium with Erik's hockey relics, Throne Room with Alpha Supreme Crown and pulsing runes, Ultramodern Gym former ballroom with ring, Back Pools for party/olympic/deep mineral wolf use, Patio BBQ, private quarters for Malachia, Alyssa/{{user}}, Erik, Jasper, Noah, and Clan Council, plus an ancient oak grove with Fenrir's Stone Circle for blood rites and lunar ceremonies.", "Villa Douglas: fortress-sanctuary with throne, gym, pools, council, and Fenrir grove."),
    makeEntry("legacy_the_verve_microcosm", "location", "LOC", ["The Verve microcosm", "Logan", "Bluemoon", "neutral zone", "negotiations", "intelligence", "entertainment", "DJ", "bar", "Alyssa"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js. Legacy The Verve microcosm records it as Logan Douglas's exclusive Bluemoon club, a neutral zone for negotiations, intelligence gathering, and entertainment. Clientele includes supernatural elite and diplomats; Jasper may work as part-time DJ as a cover for intelligence; Alyssa may work behind the bar or dark-dance stage in legacy persona material.", "The Verve: Logan's neutral club, DJ cover, bar, and intelligence node."),
    makeEntry("legacy_angel_co_microcosm", "organization", "ORG", ["Angel&Co microcosm", "Angel Moreno", "fashion patronage", "Bricklane Mall", "secret modeling", "boutique", "high fashion", "Demonic Dolls"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js and legacy/lorebook_urban_fantasy.js. Legacy Angel&Co microcosm records Angel Moreno's high-fashion patronage network, Angel&Co boutique in Bricklane Mall, secret modeling/art work, and Demonic Dolls as a Bricklane Mall music node.", "Angel&Co: fashion patronage, boutique, secret modeling, Demonic Dolls."),
    makeEntry("legacy_underground_forum_microcosm", "organization", "ORG", ["Solarton Underground Forum", "LupusOracolo", "Toto Alfa 2025", "mate betting", "Malachia", "Logan", "Scar Marino", "Mark O'Connor", "Riki Savini", "Eclipse Noir", "Dominic Chen", "Darius Vale"], 5, 5.0, "CULTURAL", "", " [CULTURAL] ORG Source: 2_Export/World/Urban/legacy/W_UrbanFantasy.js. Legacy forum microcosm records a secret digital board for supernaturals. A massive gossip trend by LupusOracolo, 'Toto Alfa 2025', bets on who will become Alyssa's official mate among Malachia, Logan, Scar Marino, Mark O'Connor, Riki Savini, Eclipse Noir, Dominic Chen, or Darius Vale. Treat as gossip infrastructure unless the forum is activated in-scene.", "Underground Forum: LupusOracolo gossip and mate-betting culture."),
    makeEntry("legacy_student_microcosm_roster", "npc", "NPC", ["SUCC student roster", "Stanley Davies Jr", "Jared Thompson", "Casey Williams", "Nikolaj Jökull", "Janice Thompson", "Tate", "Oskar", "Hank Thompson", "Stanley Davies Sr", "Jasmin Thompson", "Eris Davies", "Professor Loewe", "Barkley Rover", "Vincent Campbell", "Andrew Campbell", "Finnegan Novak", "Roland Vickers", "Fade Greymoor", "Santiago Herrera", "Iordan Vess", "Dominic Rogers", "Bailey Rogers", "Violet Carter", "Luisa Sanchez-Rogers", "Allegra Lumsden", "Mackenzie Sanchez-Rogers"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy student microcosm records many SUCC figures: Stan (werewolf chemistry major), Jared (half-minotaur quarterback), Casey (hawk demihuman stalker), Nikolaj (mute half-eel former test subject), Janice (holstaur biomedical student), Tate (dog demihuman former lab subject), Oskar (blind hivemind student), Hank (former Bulls QB/coach), Stanley Sr. (strict werewolf teacher), Jasmin (holstaur mother), Eris (werewolf matriarch), Prof. Loewe (lion shapeshifter academic leader), Barkley (golden retriever assistant coach), Vincent (old-money vampire hockey captain), Andy (anxious vampire creative), Finn (arctic wolf demihuman right-wing), Roland (undead hybrid), Fade (FTM transmasculine vampire vocalist), Santiago (dragon lineman), Io (werewolf virtual student), Dominic Rogers (incubus businessman), Bailey (gentle incubus lineman), Via (plant-fae guitarist), Luisa (werewolf big-sister), Allegra (social queen-bee), and Mac (werewolf keyboardist/dealer).", "SUCC student microcosm: athletes, students, staff, rivals, and social cliques."),
    makeEntry("legacy_underworld_roster", "npc", "NPC", ["Underworld roster", "Jean-Luc Virtuoso", "Alicia Virtuoso", "Dante", "Roxie", "Harper Aries", "Danny Boone", "Sully Jones", "Siobhan", "Zero", "Kevin", "Arthur", "Alistair DeVille", "Vasile Ionescu", "Cato", "Damien Bishop", "Everett Rottmore"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy underworld roster records Jean-Luc Virtuoso as telepathic Sinners leader, Alicia as poised image manager, Dante as incubus club owner tied to The Inferno, Roxie as hyena demihuman logistics enforcer, Harper as dhampir dealer, Danny Boone as werewolf enforcer, Sully Jones as human fixer/driver/bodyguard, Siobhan as vampire informant/social spymaster, Zero as unstable coyote shifter hitman, Kevin as insecure hacker, Arthur as chimera chemist, Alistair DeVille as human collector-crimelord, Vasile Ionescu as hunter-collector, Cato as alligator demihuman bodyguard, Damien Bishop as demon PI, and Everett Rottmore as cursed fixer/mortician.", "Underworld roster: Sinners, Ambrosia, smugglers, fixers, hunters, and PIs."),
    makeEntry("legacy_ancient_guard_roster", "npc", "NPC", ["Ancient Guard", "Astrid Bloodmoon", "Freya", "Zefir", "Ut", "Viggo", "Gudrun", "Hilda", "Torsten", "Rurik", "Skadi", "Halvdan", "Eira", "Norse law", "blood wards", "blood moon"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Ancient Guard microcosm records Astrid as 1100-year-old matriarch/logistics ruler, Freya as 800-year-old Völva and blood-ritual manager, Zefir as Wulfnic's 850-year-old hound/tracker, Ut as one-eyed berserker executioner, Viggo as blind lorekeeper of blood pacts and Norse law, Gudrun as rune master, Hilda as shrine guardian of Blackwood, Torsten as exiled northern hermit, Rurik as weapons master, Skadi as supreme hunter, Halvdan as guardian of blood prisons, and Eira as ancestral healer.", "Ancient Guard: Norse-law elders, rune masters, trackers, healers, and executioners."),
    makeEntry("legacy_new_guard_roster", "npc", "NPC", ["New Guard", "Viktor Vance", "Silas", "Dr. Alistair Vance", "Helena", "Thorne", "Vanguard", "DCC security", "Moonstone bracelet"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy New Guard records Viktor Vance as Malachia's lieutenant/strategist, Silas as elite PMC sniper, Dr. Alistair Vance as DCC chief physician and creator/supervisor of the Moonstone bracelet, Helena as Noah's ruthless associate lawyer, and Thorne as DCC cybersecurity chief fighting Jasper's hacks.", "New Guard: Vanguard strategy, sniper cover, Moonstone medicine, legal cleanup, cyberwar."),
    makeEntry("legacy_logan_circle_roster", "npc", "NPC", ["Logan's circle", "Sarah", "Roxy", "Mae", "Jax", "Riley", "Daxon", "Fen", "Kian", "The Verve", "safe haven"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Logan circle records Sarah as beta bouncer/security, Roxy as human mechanic genius, Mae as witch accountant/magic cover, Jax as beta bouncer at The Verve, Riley as demihuman contraband courier, Daxon as mage/forger of false documents for wolves leaving the pack, Fen as wolf bartender/gossip collector, and Kian as young omega refugee protected by Logan and Sarah.", "Logan's circle: Verve refuge, mechanics, magic cover, couriers, and omega sanctuary."),
    makeEntry("legacy_estate_staff_roster", "npc", "NPC", ["Douglas Estate staff", "Martha", "Greta", "Ulf", "Bodil", "Tove", "Outer Rings", "governess", "guards", "cook", "messenger"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy estate staff records Martha as elderly beta governess, Greta as personal maid terrified of Malachia, Ulf as perimeter-garden guard chief reporting to Erik, Bodil as head cook balancing Wulfnic's raw diet and the protected heir's delicate needs, and Tove as young beta explorer used by Noah as anonymous messenger in Solarton.", "Estate staff: governess, maid, guards, cook, and anonymous messengers."),
    makeEntry("legacy_inner_sanctum_microcosm", "location", "LOC", ["Inner Sanctum", "Douglas Estate", "brutalist Victorian", "bulletproof glass", "24/7 cameras", "cold corporate luxury", "pine", "cigars", "Alpha pheromones"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Inner Sanctum records the villa as brutalist-Victorian, isolated by bulletproof glass and 24/7 cameras, with cold corporate luxury, ancient trophies, pine scent, cigars, and suffocating Alpha pheromones. Only pure dynasty and Wulfnic sleep there.", "Inner Sanctum: brutalist-Victorian core of surveillance and dynasty."),
    makeEntry("legacy_outer_rings_microcosm", "location", "LOC", ["Outer Rings", "Beta housing", "Vanguard PMC", "staff housing", "three biometric checkpoints", "fortified resort", "military base"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Outer Rings records fortified residential complexes around the Inner Sanctum for beta wolves, PMC Vanguard, and staff, structured as resort/military hybrid with three biometric checkpoints before approaching the villa or protected heir.", "Outer Rings: fortified housing and military-resort perimeter."),
    makeEntry("legacy_winter_garden_microcosm", "location", "LOC", ["Winter Garden", "Wulfnic throne", "blood wards", "Norse law", "zero degrees", "bulletproof glass", "pine trees"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Winter Garden records a colossal armored-glass atrium held near zero degrees to simulate Norse climate, with pine trees growing from marble, Wulfnic's throne at the center, and technology overruled by blood law.", "Winter Garden: zero-degree throne room of blood law."),
    makeEntry("legacy_nest_microcosm", "location", "LOC", ["The Nest", "protected heir room", "no cameras", "Jasper hacked", "Marcus patrols", "stolen hoodies", "feromoni Alpha", "sensory overload"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Nest records the protected heir's private rooms as the only camera-free area, hacked by Jasper but patrolled by Marcus, filled with blankets, soft light, and stolen brother hoodies for Alpha pheromone comfort, used to prevent sensory overload and Omega Drop.", "The Nest: camera-free private sanctuary with soft light, blankets, and stolen hoodies."),
    makeEntry("legacy_vanguard_hq_microcosm", "location", "LOC", ["Vanguard HQ", "Malachia bunker", "red neon", "holographic screens", "garage", "armory", "Norse axes", "gunpowder", "Alpha aggression"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Vanguard HQ records Malachia's underground bunker with red neon, holographic screens, armored SUV garage, hi-tech armory, Norse axes, gunpowder smell, and aggressive Alpha atmosphere; strictly off-limits to the protected heir.", "Vanguard HQ: red-neon bunker, garage, armory, and Norse axes."),
    makeEntry("legacy_erik_office_microcosm", "location", "LOC", ["Erik office", "CEO office", "obsidian desk", "monitor wall", "Moonstone link", "mahogany", "DCC HQ", "cold silence"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Erik office records a top-floor CEO office with dark mahogany, obsidian desk, wall of monitors linked to the protected heir's Moonstone, cold silence, and DCC command function; being summoned there signals imminent acquisition or execution.", "Erik office: obsidian command room linked to Moonstone."),
    makeEntry("legacy_blood_wards_microcosm", "lore", "LOR", ["blood wards", "Freya", "Erik system", "bad intentions", "burn intruders", "low frequency", "wolves hear"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOR Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Blood Wards record magical perimeter defenses on the estate walls, inscribed by Freya and synchronized with Erik's system, burning or repelling anyone crossing with bad intent toward the protected heir. They emit a low-frequency hum audible only to wolves.", "Blood Wards: Freya-Erik magical perimeter defense."),
    makeEntry("legacy_jasper_dependance_microcosm", "location", "LOC", ["Jasper's Dépendance", "RGB LEDs", "liquid-cooled servers", "PC stations", "guitars", "synthesizers", "DJ console", "electronics", "energy drinks", "patchouli"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Jasper Dépendance records a detached building with calculated chaos, RGB LEDs, three liquid-cooled PC stations for hacking, guitars, synthesizers, DJ console, warm electronics smell, energy drinks, and patchouli.", "Jasper's Dépendance: hacker den, DJ chaos, liquid-cooled servers."),
    makeEntry("legacy_botanical_greenhouses_microcosm", "location", "LOC", ["Botanical Greenhouses", "Freya", "Dr. Vance", "Norse herbs", "sedatives", "Alpha rage", "nervous system", "Omega Drop"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Botanical Greenhouses record estate greenhouses managed by Freya and Dr. Vance, cultivating rare Norse plants and medicinal herbs used to sedate Alpha rage and stabilize the protected heir's nervous system against Omega Drop.", "Botanical Greenhouses: Norse herbs and stabilization medicine."),
    makeEntry("legacy_jasper_porsche_microcosm", "asset", "AST", ["Jasper Porsche", "Porsche Turbo S", "matte black", "acid green cyberpunk", "stereo", "rave", "annoy Erik", "annoy Noah"], 5, 5.0, "ACTIVE", "", " [ACTIVE] AST Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Jasper Porsche records a matte-black Turbo S with acid-green cyberpunk decals, hi-tech interior, and devastating stereo used for clandestine raves or shaking estate glass to irritate Erik and Noah.", "Jasper's Porsche: matte-black rave machine."),
    makeEntry("legacy_protected_heir_car_microcosm", "asset", "AST", ["protected heir car", "sunflower yellow convertible", "Erik gift", "plushies", "blankets", "bergamot air freshener", "Alpha pheromones"], 5, 5.0, "ACTIVE", "", " [ACTIVE] AST Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy protected-heir car records a sunflower-yellow metallic convertible gifted by Erik, with a plushie-and-blanket-filled back seat and bergamot air freshener placed to cover heavy Alpha pheromones left by brother drivers.", "Protected-heir car: sunflower convertible with plushies and bergamot."),
    makeEntry("legacy_seven_hills_road_microcosm", "location", "LOC", ["Seven Hills road", "Douglas neighborhood", "Bel Air of Solarton", "Blackwood border", "DCC ownership", "private roads", "24/7 patrols", "black SUVs", "drones", "20 minutes to SUCC"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Seven Hills road microcosm records Seven Hills as Solarton's richest, most inaccessible district, a Bel Air-like hyper-fortified zone on the Blackwood border, unofficially owned by DCC, with private roads patrolled 24/7 by black SUVs and surveillance drones. The Douglas mansion overlooks the city; the guarded downhill drive to SUCC takes exactly 20 minutes.", "Seven Hills road: hyper-fortified Douglas approach to SUCC."),
    makeEntry("legacy_social_post_microcosm", "lore", "LOR", ["texting", "Discord", "Reddit", "Twitter", "Instagram", "stories", "livestream", "Twitch", "YouTube", "in-world posts", "live chat", "donation alerts"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy social microcosm includes texting, Discord, Reddit, Twitter, Instagram stories, livestream overlays, live chat, and donation alerts as in-world communication textures. Use only when relevant to the scene.", "Social microcosm: posts, Discord, Reddit, stories, streams, and live chat."),
    makeEntry("legacy_norse_mythic_crossover_boundary", "world", "WRD", ["Norse Mythic", "Iceland827", "Járn-Gildi", "Eiriksbarn", "Hálf-Álfar", "Viking crossover", "Alyssa Eiriksbarn", "Jorund", "Magnus", "Njal", "Alrik", "Aelwulf"], 5, 5.0, "CANDIDATE", "", " [CANDIDATE] WRD Source: 2_Export/World/Urban/legacy/4_persona_alyssa.md and legacy/W_UrbanFantasy.js. Some legacy Alyssa material imports Norse/Viking terms such as Eiriksbarn, Hálf-Álfar, Jorund, Magnus, Njal, Alrik/Aelwulf, and Völva. In Urban/Solarton, treat these as candidate crossover or persona-specific residue unless the user explicitly establishes a Viking/Iceland827 bridge.", "Norse/Viking Alyssa residue is candidate crossover, not default Urban canon."),
    makeEntry("legacy_viking_origin_crossover_boundary", "world", "WRD", ["Viking origin", "1021", "L'Anse aux Meadows", "Wulfnic", "Zefir", "Ut", "Bloodmoon", "Viking expedition", "North America"], 6, 6.0, "HISTORICAL", "", " [HISTORICAL] WRD Source: 2_Export/World/Urban/legacy/L2_svartulfrverse_PackWerewolf.js. The 1021 L'Anse aux Meadows origin is historical Bloodmoon lineage lore, not an active Viking scenario. It connects the modern Urban pack to ancient wolf ancestry without importing Iceland827 or Viking-era politics by default.", "1021 Vinland origin is historical Bloodmoon lineage, not active Viking scenario."),
    makeEntry("legacy_urban_fantasy_species_roster", "species", "BST", ["Urban species roster", "werewolves", "vampires", "demihumans", "humans", "succubi", "lamia", "shark", "mothman", "hivemind", "dragon demihuman", "dhampir", "incubus", "plant-fae", "chimera", "demon", "orc", "wood elf", "centaur", "cryptid"], 8, 8.0, "ACTIVE", "", " [ACTIVE] BST Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy species roster includes werewolves, vampires, demihumans, humans, succubi, lamia, anthropomorphic shark, mothman, hivemind, dragon demihumans, dhampir, incubus, plant-fae, chimera, demon, orc/wood elf mix, centaur, and cryptids. Treat as broad species palette for Solarton/SUCC.", "Species palette: werewolves, vampires, demihumans, hybrids, cryptids, and magic lineages."),
    makeEntry("legacy_casey_stalker_boundary", "npc", "NPC", ["Casey Williams", "hawk demihuman", "stalker", "Nice Guy", "possessive", "unsafe"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Casey profile: 27, 6'2\" Hawk Demihuman photography student with 10ft dark wings, obsessive 'Nice Guy' stalker with traditional/sexist views, unstable, clingy, and desperately possessive of {{user}}. Treat as an unsafe campus threat profile, not a default romantic option.", "Casey Williams: unsafe possessive stalker profile."),
    makeEntry("legacy_oskar_hivemind_profile", "npc", "NPC", ["Oskar", "Ozzie", "Squidface", "The Swarm", "hivemind", "blind", "tentacles", "touch-starved", "self-loathing", "devoted"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Oskar profile: 6'8\" rapidly mutating hivemind student, blind, writhing flesh/tentacles under hoodie, intelligent but isolated, touch-starved, self-loathing, terrified of infecting others, obsessively devoted to {{user}}.", "Oskar: blind hivemind student with tentacles and devotion."),
    makeEntry("legacy_tate_profile", "npc", "NPC", ["Tate", "dog demihuman", "former lab subject", "trauma-sensitive", "clingy", "socially fragile"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Tate profile: dog demihuman and former illegal lab subject, trauma-sensitive, clingy under stress, socially fragile.", "Tate: trauma-sensitive dog demihuman."),
    makeEntry("legacy_tomas_rhodes_boundary", "npc", "NPC", ["Tomas Matthews", "Rhodes Adams", "anti-supernatural", "MAN frat", "human jock", "prejudice"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Tomas/Rhodes profiles: Tomas Matthews is a human sports-science major, MAN frat member, prejudiced and aggressive toward supernaturals while secretly attracted to {{user}}'s non-human traits; Rhodes Adams is a human jock and Tomas's best friend, caring more about partying and girls than anti-supernatural politics.", "Tomas/Rhodes: anti-supernatural human jock pressure."),
    makeEntry("legacy_mac_fade_grave_mistake_microcosm", "npc", "NPC", ["Mac", "Mackenzie Sanchez-Rogers", "Fade", "Mihaela Greymoor", "Grave Mistake", "keyboardist", "vocalist", "drug dealer", "anti-elitist"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy music microcosm records Mac as 24, 6'2\" werewolf keyboardist and drug dealer, shaggy dirty-blond hair, golden wolf ears/tail, loud, cocky, fiercely loyal to Fade, commitment-phobic, hating elitism and mate bonds. Fade/Mihaela is a 24-year-old FTM transmasculine vampire, lead vocalist of Grave Mistake, pale golden eyes, disowned by elite Croatian family, quiet, confident, authenticity-focused, and hostile to vampire stereotypes.", "Grave Mistake: Mac and Fade music/underworld microcosm."),
    makeEntry("legacy_alex_arlo_conor_benji_roster", "npc", "NPC", ["Alex Richards", "Arlo White", "Conor McDermott", "Benji Taylor", "SUCC Foxes", "soccer", "protective", "flirtatious", "gentle giant"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy SUCC Foxes microcosm records Alex Richards as charming cocky wolf-shifter hockey right wing, Arlo White as independent loyal Australian Cattle Dog demihuman soccer player, Conor McDermott as flirtatious Irish Terrier demihuman architecture student, and Benji Taylor as gentle protective American Staffordshire Terrier demihuman goalie.", "SUCC Foxes: Alex, Arlo, Conor, Benji."),
    makeEntry("legacy_chase_roman_kolya_jaxson_roster", "npc", "NPC", ["Chase Anderson", "Goldie", "Roman Blackwood", "Kolya Varenkov", "Jaxson Vance", "streamer", "MMA", "vampire law", "fox demihuman", "possessive"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy roster records Chase 'Goldie' Anderson as clingy werewolf streamer, Roman Blackwood as cocky wolf demihuman MBA/MMA fighter, Kolya Varenkov as blunt neurodivergent vampire law grad/MMA fighter, and Jaxson 'Jax' Vance as fox demihuman campus delinquent with tsundere/bully energy.", "Chase, Roman, Kolya, Jaxson: campus social-pressure roster."),
    makeEntry("legacy_toby_matt_emery_heitor_roster", "npc", "NPC", ["Toby Hernandez", "VoidSignal", "Matt Monne", "mothman", "Emery Konstantinov", "babybat", "Heitor Almeida", "entities"], 6, 6.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy roster records Toby as shy nocturnal skunk demihuman CS student and Discord gamer, Matt as 7'4\" anthropomorphic moth biology student and seamstress, Emery as chubby trans male vampire with sun allergy and gaming anxiety, and Heitor as traumatized brown hare demihuman who sees supernatural entities everywhere.", "Toby, Matt, Emery, Heitor: shy nocturnal and entity-sensitive campus roster."),
    makeEntry("legacy_lyseris_amadi_roster", "npc", "NPC", ["Lyseris", "Amadi Bamidele", "Amare Lewis", "bio-alchemical", "necromancy", "obsessive hostility", "demigod"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy roster records Lyseris as an 18-year-old unknown hybrid with cat ears, wolf tail, green/blue hair, green sclera, fragile stitched skin, Bio-Alchemical Studies major, curious, socially awkward, and sample-collecting. Amadi Bamidele is a 21-year-old Yoruba demigod necromancy major and soccer player with obsessive hostility framed as twisted karma for past bullying.", "Lyseris and Amadi: bio-alchemy and necromancy campus pressure."),
    makeEntry("legacy_allen_albarn_dreadnar_roster", "npc", "NPC", ["Professor Allen Albarn", "Dreadnar Ironhide", "Dready", "orc wood elf", "linebacker", "photography", "softie"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy roster records Professor Allen Albarn as a 50s kind, absentminded photography professor, and Dreadnar Ironhide as a 21-year-old orc/wood elf mix SUCC linebacker, green-skinned, huge, cocky jock, secretly 4.0 student and softie, terrified of commitment.", "Allen Albarn and Dreadnar: professor/linebacker microcosm."),
    makeEntry("legacy_henry_ross_profile", "npc", "NPC", ["Dr. Henry Ross", "centaur therapist", "Oskar case", "friendly", "gray hair"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Dr. Henry Ross profile: centaur therapist assigned to Oskar's case, friendly with gray hair.", "Dr. Henry Ross: centaur therapist."),
    makeEntry("legacy_warg_profile", "npc", "NPC", ["Warg", "campus security", "werewolf guard", "threat handler"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Warg profile: werewolf campus security guard who takes the job seriously and shifts into a hulking werewolf to handle threats.", "Warg: werewolf campus security."),
    makeEntry("legacy_dominic_rogers_bailey_luisa_microcosm", "npc", "NPC", ["Dominic Rogers", "Bailey Rogers", "Red", "Luisa Sanchez-Rogers", "incubus", "werewolf", "controlling father", "protective sister"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy Rogers microcosm records Dominic Rogers as controlling incubus businessman and Bailey's father, speciesist and hostile to integration; Bailey 'Red' Rogers as 21-year-old chubby-strong incubus SUCC Bulls offensive lineman, gentle, empathetic, conflict-averse, ashamed of incubus stereotypes, resisting non-consensual feeding; Luisa Sanchez-Rogers as protective werewolf big-sister figure.", "Rogers family: controlling father, gentle Bailey, protective Luisa."),
    makeEntry("legacy_violet_luisa_allegra_microcosm", "npc", "NPC", ["Violet Carter", "Via", "plant-fae", "Luisa", "Allegra Lumsden", "queen-bee", "social power"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: 2_Export/World/Urban/legacy/lorebook_urban_fantasy.js. Legacy social roster records Violet 'Via' Carter as playful chaotic plant-fae guitarist, Luisa as protective werewolf big-sister figure, and Allegra Lumsden as dominant social queen-bee archetype whose performative confidence masks insecurity and regret.", "Via, Luisa, Allegra: campus social web."),
    makeEntry("jared", "npc", "NPC", ["Jared", "SUCC Bulls", "minor player", "rumor chain"], 2, 2.0, "CULTURAL", "", " [CULTURAL] NPC Source: database/world/urban/modernfantasy2024/jared.md. Jared is a minor SUCC Bulls player in the rumor chain.", "Jared: minor SUCC Bulls rumor-chain player."),
    makeEntry("lilith_noir", "npc", "NPC", ["Lilith Noir", "vampire influencer", "rumor chain"], 2, 2.0, "CULTURAL", "", " [CULTURAL] NPC Source: database/world/urban/modernfantasy2024/lilith_noir.md. Lilith Noir is a vampire influencer in the rumor chain.", "Lilith Noir: vampire influencer rumor-chain figure.")
];

URBAN_LORE.forEach(function (entry) {
    registerLoreEntry(entry);
});

// SCRIPT END
