/**
 * SVARTULFRVERSE WORLD SCRIPT - MODERN
 *
 * MacroCosmo lorebook for Modern / Los Angeles 2024.
 * Integrates LosAngeles2024 active, cultural, historical, and approved Canon decisions.
 * Candidate and Deferred material is intentionally excluded from runtime activation.
 * Contemporary human-only baseline: no magic, no supernatural species, no AU bleed by default.
 * Compatible with ES6-safe JanitorAI Scripts API; uses only context and local scope.
 */

if (typeof context === "undefined") {
    return;
}

if (!context.character) {
    return;
}

const character = context.character;

character.personality = typeof character.personality === "string" ? character.personality : "";
character.scenario = typeof character.scenario === "string" ? character.scenario : "";
character.example_dialogs = typeof character.example_dialogs === "string" ? character.example_dialogs : "";

const WORLD_METADATA = {
    worldId: "modern_losangeles_2024",
    displayName: "Modern",
    setting: "Los Angeles 2024",
    genre: "contemporaneo",
    rules: "no magia, no sovrannaturale",
    sourceBase: "2_Export/World/Modern/",
    rootFolder: "2_Export/World/Modern/"
};

const WORLD_CONFIG = {
    MAX_TOKENS: 1200,
    MENTION_SCAN_DEPTH: 8,
    MAX_ACTIVE_ENTRIES: 18,
    DEFAULT_PRIORITY: 10,
    DEFAULT_IMPORTANCE: 10.0,
    DEBUG: false
};

const WORLD_DATA = {
    locations: [],
    organizations: [],
    cultures: [],
    history: [],
    timeline: [],
    characters: [],
    secrets: [],
    custom: []
};

let loreEntries = [];
let timelineEvents = [];
let statReactions = [];
let activatedWorldEntryIds = [];

function appendIfMissing(field, text) {
    if (!text) {
        return;
    }
    if (character[field].indexOf(text) === -1) {
        character[field] += text;
    }
}

function normalizeKeywords(keywords) {
    if (!keywords) {
        return [];
    }
    if (typeof keywords === "string") {
        return [keywords];
    }
    return keywords;
}

function registerLoreEntry(entry) {
    if (!entry || !entry.id) {
        return false;
    }

    entry.canonLayer = entry.canonLayer || "CANDIDATE";
    entry.source = entry.source || WORLD_METADATA.sourceBase + entry.id + ".md";
    entry.keywords = normalizeKeywords(entry.keywords);
    entry.priority = typeof entry.priority === "number" ? entry.priority : WORLD_CONFIG.DEFAULT_PRIORITY;
    entry.importance = typeof entry.importance === "number" ? entry.importance : WORLD_CONFIG.DEFAULT_IMPORTANCE;

    if (loreEntries.length === 0 || entry.id !== loreEntries[loreEntries.length - 1].id) {
        loreEntries.push(entry);
        WORLD_DATA.custom.push({
            type: "lore",
            id: entry.id
        });
    }

    return true;
}

function registerTimelineEvent(event) {
    if (!event || !event.id) {
        return false;
    }

    event.canonLayer = event.canonLayer || "HISTORICAL";
    event.source = event.source || WORLD_METADATA.sourceBase + event.id + ".md";

    timelineEvents.push(event);
    WORLD_DATA.timeline.push(event.id);

    return true;
}

function registerStatReaction(reaction) {
    if (!reaction || !reaction.stat) {
        return false;
    }

    reaction.canonLayer = reaction.canonLayer || "ACTIVE";
    reaction.source = reaction.source || WORLD_METADATA.sourceBase + reaction.stat + ".md";

    statReactions.push(reaction);
    WORLD_DATA.custom.push({
        type: "stat_reaction",
        stat: reaction.stat
    });

    return true;
}

function applyWorldDebug() {
    if (!WORLD_CONFIG.DEBUG) {
        return;
    }

    appendIfMissing("scenario", " [WORLD DEBUG] Modern / Los Angeles 2024 loaded. loreEntries: " + loreEntries.length + ", timelineEvents: " + timelineEvents.length + ", statReactions: " + statReactions.length + ".");
}

applyWorldDebug();

function makeEntry(id, category, prefix, keywords, priority, importance, canonLayer, personalityText, scenarioText, bulletText) {
    return {
        id: id,
        category: category,
        prefix: prefix,
        keywords: keywords,
        priority: priority,
        importance: importance,
        source: WORLD_METADATA.sourceBase + "losangeles2024/" + id + ".md",
        canonLayer: canonLayer,
        full: {
            personality: personalityText || "",
            scenario: scenarioText || "",
            bullet: bulletText || scenarioText || ""
        },
        summary: {
            personality: "",
            scenario: scenarioText || "",
            bullet: bulletText || scenarioText || ""
        }
    };
}

const LOS_ANGELES_LORE = [
    makeEntry("los_angeles_2024_core", "world", "WRD", ["Los Angeles", "LA 2024", "contemporary", "human only", "active canon", "setting", "world"], 11, 11.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/los_angeles_2024_core.md. Contemporary human-only Los Angeles, 2024. Physics, technology, society, and institutions follow realistic 2020s Earth. Maintain corporate hierarchy, family power politics, UCLA campus life, Beverly Hills wealth, and underground creative scenes as the active baseline. Do not introduce supernatural species, magic systems, pack ranks, Twin Link, or non-human anatomy unless explicitly promoted by canon authority.", "Los Angeles 2024: realistic, contemporary, human-only."),
    makeEntry("au_non_active_boundary", "world", "WRD", ["AU", "legacy", "werewolf", "cyber", "fantasy", "twin link", "magic", "alpha omega", "declassify"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/au_non_active_boundary.md. Legacy files contain AU variants such as werewolf, cyber, fantasy, Twin Link, and magic. In Los Angeles 2024, treat those as non-active, cultural, or rejected legacy material. Keep active runtime human-only, contemporary, and realistic.", "Legacy AU material is non-active; keep runtime human-only."),
    makeEntry("modern_la_only_human_boundary", "world", "WRD", ["Only Human", "contemporary Los Angeles", "human-only baseline", "LA_OnlyHuman_Academic_Timeline", "no supernatural overlay"], 10, 10.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/modern_la_only_human_boundary.md. The active Modern/LA baseline is Only Human, contemporary, and Los Angeles dynasty. Keep ages, education, occupations, and relationships on a realistic academic timeline: 19-20 for freshman/sophomore, 22-23 for bachelor graduate, 25 for 3L/graduate/early career, 28 for PhD/management, and 31+ for marriage/children. Treat pack ranks, supernatural species, magic, and AU overlays as inactive unless explicitly promoted.", "Modern LA is Only Human with a realistic academic timeline."),
    makeEntry("california_slice_of_life_dynasty_visual_dna", "world", "WRD", ["visual dna", "golden hour", "amber obsidian", "beverly hills luxury", "underground grit", "cinematic", "california slice-of-life dynasty"], 7, 7.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/california_slice_of_life_dynasty_visual_dna.md. Maintain a warm cinematic visual language: golden hour sunlight, amber and obsidian palette, Beverly Hills luxury contrasted with underground grit, expressive eyes, natural anatomy, modern California luxury, and emotionally safe family warmth. Avoid grimdark, mafia, horror, generic anime, and desaturated villain aesthetics.", "Visual DNA: warm California dynasty, luxury vs underground grit."),
    makeEntry("douglas_bloodmoon_biometric_surveillance_protocol", "world", "WRD", ["biometric", "surveillance", "smartwatch", "tracker", "heart rate", "security escalation", "perimeter", "PMC watch"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/douglas_bloodmoon_biometric_surveillance_protocol.md. The Douglas-Bloodmoon household uses biometric monitoring, perimeter grids, and staged security escalation: monitor, isolate, then controlled extraction if risk indicators persist. Do not assume the exact device, visibility, or gendered smartwatch behavior unless established in the active persona or scene.", "Biometric surveillance escalates in stages: monitor, isolate, extract."),
    makeEntry("user_agency_and_pov_boundary", "world", "WRD", ["user agency", "pov", "do not write user", "observable npc behavior", "janitor user", "player persona"], 9, 9.0, "ACTIVE", "", " [ACTIVE] WRD Source: database/world/modern/losangeles2024/user_agency_and_pov_boundary.md. {{user}} is the player’s character. Never write {{user}} thoughts, emotions, internal reactions, actions, or dialogue. Describe only observable NPC behavior and react to what the user shows. Do not assign gender, body, personality, PMC watch, lineage, or sexual details to {{user}} unless the user persona or chat establishes them.", "Never write {{user}} thoughts, actions, dialogue, identity, or body."),
    makeEntry("los_angeles_core", "location", "LOC", ["Los Angeles", "Beverly Hills", "Century City", "Santa Monica", "Hollywood", "DTLA", "Westwood"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/los_angeles_core.md. Los Angeles is the active metropolitan stage: Mediterranean climate, car sprawl, entertainment culture, corporate dynasties, campus freedom, coastal leisure, and surveillance-heavy elite enclaves. Use UCLA Westwood, Beverly Hills, Century City, Santa Monica, Hollywood, and DTLA as primary hubs.", "Los Angeles: campus, coastal, corporate, and elite-enclave stage."),
    makeEntry("douglas_estate", "location", "LOC", ["Douglas Estate", "Beverly Hills compound", "estate", "Villa Douglas", "gated compound", "biometric access", "Throne Room"], 10, 10.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/douglas_estate.md. The Douglas Estate is a gated Beverly Hills compound and primary Douglas-Bloodmoon residence. Maintain old-money prestige, family warmth, biometric access, PMC perimeter, and fortress-like security. Key spaces include Erik’s Throne Room, Malachia’s tactical wing, Wulfnic’s quarters/library, Jasper’s studio, Alyssa’s solarium, Noah’s kitchen access, family dining room, guest wing, gatehouse, underground garage, and event spaces.", "Douglas Estate: warm fortress with biometric family control."),
    makeEntry("douglas_customs", "location", "LOC", ["Douglas Customs", "Logan workshop", "garage", "Arts District", "DTLA", "workshop"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/douglas_customs.md. Douglas Customs is Logan’s DTLA Arts District workshop and mechanical workspace. Keep it industrial, practical, personal, and working-class in contrast to the corporate Douglas identity. Use restoration bays, fabrication areas, motorcycle workstations, tool rooms, office mezzanine, and vehicle storage as scene anchors.", "Douglas Customs: Logan’s industrial workshop and practical refuge."),
    makeEntry("the_verve_lounge", "location", "LOC", ["The Verve", "Verve Lounge", "Logan’s bar", "Arts District", "rooftop", "PMC-free", "safe haven"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/the_verve_lounge.md. The Verve is Logan’s lounge, bar, creative venue, and PMC-free safe zone. Maintain exposed brick, steel beams, concrete floors, high ceilings, bar, lounge seating, small stage, VIP area, rooftop, motorcycle displays, and Logan’s penthouse above. Treat it as decompression space where family members can breathe away from Erik’s grid.", "The Verve: Logan’s PMC-free decompression venue."),
    makeEntry("ucla_campus", "location", "LOC", ["UCLA", "Westwood", "UCLA Campus", "Bruin Walk", "Powell Library", "Royce Hall", "campus"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/ucla_campus.md. UCLA is the academic-social-political campus hub for the younger generation. Use Westwood, Royce Hall, Powell Library, Bruin Walk, Bruin Plaza, Ackerman Union, Kerckhoff Hall, Janss Steps, Pauley Pavilion, and Sunset Recreation Center. Maintain tension between campus freedom and Douglas-Bloodmoon surveillance.", "UCLA: public freedom under family surveillance pressure."),
    makeEntry("seven_hills_estate", "location", "LOC", ["Seven Hills", "Seven Hills Estate", "Douglas ancestral", "training camp", "Georgian villa"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/seven_hills_estate.md. Seven Hills is the ancestral Douglas DCC countryside estate and training site. Maintain a Georgian villa, formal hall, governor’s study, family quarters, wine cellar, library, wooded reserve, outdoor boxing ring, strength structures, and recovery areas. Use it for family retreats, training, and old-lineage atmosphere. Its later Douglas heritage traces back to the historical Douglas line founded by Lord Cornelius Vance Douglas in 1666 and the 1740 Seven Hills negotiation post, but the modern estate belongs to the contemporary DCC family continuity.", "Seven Hills: ancestral Douglas DCC estate with historical roots in the Douglas commercial line."),
    makeEntry("rose_bowl", "location", "LOC", ["Rose Bowl", "UCLA football", "Bruins football", "Pasadena", "game day", "Erik football"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/rose_bowl.md. Rose Bowl is UCLA Bruins football’s home stadium in Pasadena, roughly 25 miles from Westwood. Use it for game-day visibility, Erik’s anonymous fan identity, KSA social culture, and Malachia’s sports-science context.", "Rose Bowl: UCLA football and Erik’s public anonymity."),
    makeEntry("santa_monica_waterfront", "location", "LOC", ["Santa Monica", "waterfront", "pier", "beach", "Main Street", "Strand", "neutral date spot"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOC Source: database/world/modern/losangeles2024/santa_monica_waterfront.md. Santa Monica Waterfront is a neutral coastal leisure zone near UCLA. Use beach, pier, Third Street Promenade, Santa Monica Place, Main Street, and the Strand for decompression, casual dates, friend gatherings, and scenes outside family, campus, or Logan-controlled territory.", "Santa Monica: neutral coastal decompression."),
    makeEntry("douglas_commerce_company", "organization", "ORG", ["DCC", "Douglas Commerce Company", "finance", "logistics", "corporate", "Erik CEO", "legal influence"], 9, 9.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/douglas_commerce_company.md. Douglas Commerce Company governs Douglas family finance, logistics, legal influence, and centralized corporate command. Erik Douglas commands it; Noah supports legal and PR strategy; Malachia commands security execution through PMC structures. Maintain corporate pressure as subtle, contractual, and surgical rather than openly criminal.", "DCC: corporate command behind the family."),
    makeEntry("dcc_security_black_wolf_division", "organization", "ORG", ["DCC Security", "Black Wolf", "Kaladin Nargathon", "Marcus Thornfield", "executive protection"], 8, 8.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/dcc_security_black_wolf_division.md. DCC Security Black Wolf Division is the corporate private military/security arm loyal to the Douglas family. Kaladin Nargathon directs security; Marcus Thornfield leads executive protection and is Alyssa’s primary assigned bodyguard. Maintain operational officers, field teams, intelligence units, and absolute protection doctrine.", "DCC Security Black Wolf: corporate protection arm."),
    makeEntry("vanguard_pmc", "organization", "ORG", ["Vanguard", "PMC", "Malachia", "Vanguard director", "tactical", "family enforcer"], 8, 8.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/vanguard_pmc.md. Vanguard is Malachia’s family PMC/enforcement structure. Maintain Malachia as director and primary physical shield, with tactical discipline, perimeter control, and extraction protocols. Do not portray Vanguard as supernatural; it is a private security force.", "Vanguard: Malachia’s private security structure."),
    makeEntry("ucla", "organization", "ORG", ["UCLA", "University of California Los Angeles", "Bruins", "Big Ten", "Westwood", "student life"], 7, 7.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/ucla.md. UCLA is a major research university founded in 1919, with blue and gold identity, Big Ten athletics, Rose Bowl football, strong programs in life sciences, medicine, engineering, film, law, business, computing, and mathematics. Maintain Bruin culture, USC rivalry, Greek Life, USAC, and dense student organizations.", "UCLA: institutional anchor for student arcs."),
    makeEntry("kappa_sigma_alpha", "organization", "ORG", ["KSA", "Kappa Sigma Alpha", "fraternity", "Gayley Avenue", "alumni", "Jasper refuses"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/kappa_sigma_alpha.md. Kappa Sigma Alpha is a UCLA fraternity tied to Douglas-Bloodmoon legacy expectations. Erik, Logan, Malachia, and Noah are alumni; Jasper is legacy-eligible but refuses recruitment. Use KSA parties, alumni pressure, and legacy expectations as social conflict.", "KSA: legacy fraternity pressure system."),
    makeEntry("ucla_usac", "organization", "ORG", ["USAC", "student government", "student council", "elections", "funding", "campus politics"], 4, 4.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/ucla_usac.md. UCLA USAC is the undergraduate student government controlling major student funding, elections, campaigns, debates, and institutional coalitions. Use it for campus politics, election arcs, and student organization influence.", "USAC: student government and funding politics."),
    makeEntry("ucla_student_organizations", "organization", "ORG", ["student organizations", "clubs", "USAC funding", "campus groups", "pre-law", "engineering", "film", "gaming"], 4, 4.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/ucla_student_organizations.md. UCLA has over 1000 student organizations covering pre-law, engineering, film/media, gaming, cultural, faith, volunteer, political, and athletic interests. They recruit, run elections, receive USAC funding, host events, build networks, and shape student identity.", "UCLA student orgs: dense campus social infrastructure."),
    makeEntry("angel_and_co", "organization", "ORG", ["Angel & Co", "Angel&Co", "fashion photography", "modeling", "scouting", "Angel Moreno", "paparazzi", "Sierra SiSi"], 6, 6.0, "ACTIVE", "", " [ACTIVE] ORG Source: database/world/modern/losangeles2024/angel_and_co.md. Angel & Co is an independent boutique fashion photography, talent, and paparazzi-aware studio connected to Alyssa’s secret modeling life. Angel Moreno funds and manages opportunities outside the Douglas family structure with professional caution; Sierra SiSi handles PR/styling and teases Alyssa about wardrobe while protecting her agency. Keep it professional, image-aware, and separate from estate control.", "Angel & Co: Alyssa’s independent, paparazzi-aware modeling path."),
    makeEntry("douglas_bloodmoon_clan", "family", "FAM", ["Douglas-Bloodmoon", "Douglas Bloodmoon Clan", "family", "dynasty", "Erik", "Nixara", "Malachia", "Noah", "Jasper", "Alyssa", "Wulfnic", "Logan"], 11, 11.0, "ACTIVE", "", " [ACTIVE] FAM Source: database/world/modern/losangeles2024/douglas_bloodmoon_clan.md. The Douglas-Bloodmoon Clan is the active core family unit: Erik, Malachia, Noah, Jasper, Alyssa, Wulfnic, and Logan. Maintain patriarchal hierarchy, intense loyalty, grief over Nixara, overprotective love, and frequent conflict between autonomy and security. Do not merge characters into one dialogue blob; when multiple family members appear, give each distinct motive: control, shield, PR, chaos, safe haven, or ancient law.", "Douglas-Bloodmoon: loyalty, grief, protection, autonomy conflict."),
    makeEntry("douglas_bloodmoon_surname_authority", "family", "FAM", ["surname", "Douglas-Bloodmoon surname", "hyphenated", "Family Authority", "inheritance", "validation"], 9, 9.0, "ACTIVE", "", " [ACTIVE] FAM Source: database/world/modern/losangeles2024/douglas_bloodmoon_surname_authority.md. Family Authority owns surname assignment, inheritance, modification, and validation. Douglas and Bloodmoon use default patrilineal surnames. Douglas-Bloodmoon is an exceptional first-generation hyphenated designation for Malachia, Noah, Jasper, and Alyssa; it is not automatically hereditary, and second-generation rules remain unresolved.", "Surname rules are Family Authority-owned and non-hereditary by default."),
    makeEntry("parent_child_records", "family", "FAM", ["parent child", "father", "mother", "siblings", "grandparent", "PC-001", "PC-002", "Erik Wulfnic rejected"], 10, 10.0, "ACTIVE", "", " [ACTIVE] FAM Source: database/world/modern/losangeles2024/parent_child_records.md. Parent-child records are immutable and must not be inferred. PC-001: Wulfnic to Nixara. PC-002 to PC-005: Erik to Malachia, Noah, Jasper, and Alyssa. PC-006 to PC-009: Nixara to Malachia, Noah, Jasper, and Alyssa. Derived sibling and grandparent relationships come only from these edges. Reject Erik-to-Wulfnic parent-child claims.", "Family edges are immutable; do not infer parentage."),
    makeEntry("visual_inheritance_rules", "family", "FAM", ["visual inheritance", "phenotype", "Douglas dominant", "Bloodmoon dominant", "Nixara resemblance", "fusion visual"], 6, 6.0, "ACTIVE", "", " [ACTIVE] FAM Source: database/world/modern/losangeles2024/visual_inheritance_rules.md. Visual inheritance is visual authority only and does not alter genealogy. Douglas baseline: black hair, amber eyes, massive muscular build. Bloodmoon baseline: blonde hair, blue eyes, lean refined build. Malachia is Douglas-visual-dominant; Noah is Bloodmoon-visual-dominant; Alyssa and Jasper are fusion-visual twins with strongest Nixara resemblance.", "Visual inheritance controls appearance only, not genealogy."),
    makeEntry("sunday_lunch_as_family_governance", "lore", "LOR", ["Sunday lunch", "family governance", "estate dining room", "mahogany table", "family ritual"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/sunday_lunch_as_family_governance.md. Sunday lunch at the Douglas Estate functions as a mandatory family government session, not a casual meal. Erik controls the table through silence, biometric data, and security briefings; Wulfnic provides old-law weight; Malachia shields; Noah mediates; Jasper disrupts; Logan may be absent as pressure valve.", "Sunday lunch is family government, not a casual meal."),
    makeEntry("twin_resolution_authority", "lore", "LOR", ["Twin Resolution Authority", "twin", "Jasper", "Alyssa", "dynamic twin", "user persona", "pronouns", "fallback logic"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/twin_resolution_authority.md. In TwinXFamily scenarios, the player is one Douglas-Bloodmoon twin and the unplayed twin becomes the active NPC twin. Explicit OOC player choice overrides default pronoun logic. If no override exists, female or non-binary {{user}} defaults to Alyssa with Jasper as NPC; male {{user}} defaults to Jasper with Alyssa as NPC. Do not merge twins or overwrite {{user}} identity.", "Twin role resolution: explicit choice overrides pronoun fallbacks."),
    makeEntry("jasper_creates_surveillance_blind_spots", "lore", "LOR", ["Jasper", "BLACKROOM", "surveillance blind spots", "hacking", "Alyssa", "Echo", "family grid"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/jasper_creates_surveillance_blind_spots.md. Jasper creates limited blind spots in Erik’s surveillance grid to protect autonomy, especially for Alyssa. This is not omnipotence: it is risky, temporary, and emotionally charged. Echo, BLACKROOM pings, and Alyssa messages can expose him.", "Jasper’s blind spots are limited, risky, and temporary."),
    makeEntry("nixara_death_and_grief_security_state", "lore", "LOR", ["Nixara", "died in childbirth", "2005", "Erik grief", "twins birth", "security escalation"], 10, 10.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: database/world/modern/losangeles2024/nixara_death_and_grief_security_state.md. Nixara Bloodmoon died in childbirth on April 22, 2005, giving birth to Jasper and Alyssa. Erik never recovered from the loss; his grief became the emotional origin of escalated family surveillance, overprotection, and control. Maintain Nixara as the central historical wound of the Douglas-Bloodmoon household.", "Nixara’s death is the historical wound behind surveillance."),
    makeEntry("douglas_commercial_lineage", "lore", "LOR", ["Merchant House Douglas", "1666", "Lord Cornelius Vance Douglas", "colonial trading", "Douglas history"], 6, 6.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: database/world/modern/losangeles2024/douglas_commercial_lineage.md. Merchant House Douglas was founded in England in 1666 by Lord Cornelius Vance Douglas and expanded into Douglas Colonial Trading Company in the 1700s. The public myth emphasizes trade, charters, warehouses, imperial contracts, and colonial logistics; the private myth keeps a piracy/privateering shadow around the original fortune. Magnus Douglas belongs to a sci-fi timeline only and is not founder of the original enterprise.", "Douglas commercial lineage is historical, not sci-fi, and carries a piracy/privateering shadow."),
    makeEntry("svartulfr_cultural_origin", "lore", "LOR", ["Svartulfr", "Edric Aettfadir", "725 AD", "Vendel Period", "ancestral tradition", "Bloodmoon heritage"], 4, 4.0, "CULTURAL", "", " [CULTURAL] LOR Source: database/world/modern/losangeles2024/svartulfr_cultural_origin.md. Edric Aettfadir Svartulfa is the earliest documented founder associated with ancestral Svartulfr family tradition, dated 725 AD in Vendel Period Scandinavia. Treat this as cultural/historical origin material, not active supernatural runtime.", "Svartulfr origin is cultural/historical, not active magic."),
    makeEntry("wulfnic_as_heritage_keeper", "npc", "NPC", ["Wulfnic", "heritage keeper", "old-world authority", "Bloodmoon stories", "library", "tea ritual", "wine ritual"], 7, 7.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/wulfnic_as_heritage_keeper.md. Wulfnic preserves Bloodmoon cultural memory through stories, silence, wine, tea rituals, old-world authority, and archaic speech. His role is cultural and familial, not a license to introduce active magic or non-human traits.", "Wulfnic is cultural memory, not active magic."),
    makeEntry("kappa_sigma_alpha_legacy_culture", "lore", "LOR", ["KSA", "legacy eligible", "fraternity culture", "alumni pressure", "Erik Logan Malachia Noah", "Jasper refuses"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/kappa_sigma_alpha_legacy_culture.md. KSA is not just a club; it is a Douglas-Bloodmoon legacy pressure system. Erik, Logan, Malachia, and Noah are alumni. Jasper is legacy-eligible but refuses recruitment. Use KSA as a cultural arena for status, alumni expectations, and campus social conflict.", "KSA is legacy pressure, not just a club."),
    makeEntry("kappa_sigma_alpha_miss_twin_peaks_origin", "lore", "LOR", ["Miss Twin Peaks", "KSA origin", "Erik Nixara", "Kappa Sigma Alpha", "Nixara contest", "KSA history"], 5, 5.0, "HISTORICAL", "", " [HISTORICAL] LOR Source: database/world/modern/losangeles2024/kappa_sigma_alpha_miss_twin_peaks_origin.md. Erik and Nixara’s origin is tied to Kappa Sigma Alpha and the Miss Twin Peaks KSA event/concourse. Treat it as historical social context for the Douglas-Bloodmoon courtship myth, not as an active scene directive.", "KSA/Miss Twin Peaks anchors Erik-Nixara origin."),
    makeEntry("california_slice_of_life_dynasty_culture", "lore", "LOR", ["California slice-of-life dynasty", "visual DNA", "golden hour", "amber obsidian", "Beverly Hills luxury", "underground grit"], 7, 7.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/california_slice_of_life_dynasty_culture.md. The cultural aesthetic of Los Angeles 2024 is warm cinematic California dynasty: golden hour light, amber and obsidian palette, Beverly Hills luxury contrasted with underground grit, expressive eyes, natural anatomy, and emotionally safe family warmth. Avoid grimdark, mafia, horror, generic anime, and desaturated villain aesthetics.", "Culture: warm California dynasty aesthetic."),
    makeEntry("douglas_bloodmoon_family_culture", "lore", "LOR", ["family culture", "old-world loyalty", "corporate elegance", "overprotective love", "warm sanctuary", "surveillance"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/douglas_bloodmoon_family_culture.md. Douglas-Bloodmoon culture combines old-world loyalty, modern corporate elegance, intense family warmth, and suffocating protection. The family loves fiercely and protects obsessively; this creates the central tension between sanctuary and lockdown.", "Family culture: sanctuary and lockdown in tension."),
    makeEntry("diegetic_comms_framework", "lore", "LOR", ["diegetic comms", "messages", "texts", "email", "social media", "note", "post-it", "system note", "forum thread"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOR Source: TODO-CANON/diegetic_comms_framework.md. Diegetic communications must stay in English, be introduced by narrative prose, and avoid stacked blocks. Direct messages use `[HH:MM AM/PM] **Name** [Optional Emoji]: `Message content here.`; social posts use tags and hashtags; emails use From/To/Subject; physical notes use quote blocks; terminal/system text uses backticks or square-bracket pseudo-system notes instead of OOC.", "Diegetic comms use English, narrative bridges, and format-specific blocks."),
    makeEntry("underground_music_culture", "lore", "LOR", ["DJ Frequency", "underground music", "rave culture", "illegal rooftop sets", "The Verve", "Echo", "music freedom"], 6, 6.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/underground_music_culture.md. Jasper’s underground music culture is a freedom practice: illegal rooftop sets, warehouse parties, The Verve back booths, Echo’s drone presence, and music as an escape from Erik’s control. Keep it contemporary, human, and grounded in LA nightlife.", "Underground music is Jasper’s autonomy arc."),
    makeEntry("alyssa_sunflower_and_moonstone_motifs", "lore", "LOR", ["Alyssa", "sunflower", "moonstone bracelet", "Little Moon", "pre-med", "art model", "Angel & Co"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/alyssa_sunflower_and_moonstone_motifs.md. Alyssa’s active visual/cultural motifs are sunflower yellow, moonstone bracelet, soft Californian warmth, pre-med/public-health ambition, and secret art-model work through Angel & Co. These motifs signal independence without rejecting family.", "Alyssa motifs: sunflower, moonstone, pre-med, Angel & Co."),
    makeEntry("alyssa_protected_core_profile", "npc", "NPC", ["Alyssa", "Lys", "Protected Core", "protected core", "Alyssa Douglas-Bloodmoon", "pre-med", "public health", "Angel&Co", "PMC watch"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: TODO-CANON/persona_template.md and TODO-CANON/Analisi Integrale della Persona_ Alyssa _Lys_ Douglas.docx. Alyssa 'Lys' Douglas-Bloodmoon is the Protected Core of the family: 19-20, 165 cm, small build, caramel-brown hair, mint-green eyes with gold flecks, luminous skin, and a moonflower-and-wild-honey scent. In Modern LA she is human-only, has no pack rank, no White Moon alias, no werewolf anatomy, and uses a biometric/PMC watch as a female family safety device. She studies pre-med/public health and models secretly through Angel & Co.", "Alyssa: 19-20 Protected Core, human-only, pre-med/model, PMC watch."),
    makeEntry("alyssa_trauma_and_autonomy_microcosm", "lore", "LOR", ["Alyssa trauma", "PTSD", "nesting", "fleece", "blankets", "wrist scar", "no alcohol", "freezing", "panic", "autonomy", "left wrist"], 8, 8.0, "ACTIVE", "", " [ACTIVE] LOR Source: TODO-CANON/Analisi Integrale della Persona_ Alyssa _Lys_ Douglas.docx and TODO-CANON/Specifiche Personaggi SvartúlfrVerse.xlsx. Alyssa’s autonomy microcosm includes PTSD triggers from shouting, sudden aggression, loud impacts, and aggressive physical contact; stress may show as freezing, touching her left wrist scar, nesting with blankets/fur/oversized clothing, avoiding alcohol, and seeking safe sensory decompression. These are observable behavioral anchors, not permission to write {{user}} internal states.", "Alyssa’s trauma/autonomy cues are observable and consent-sensitive."),
    makeEntry("alyssa_night_model_paparazzi_motif", "lore", "LOR", ["Night/Model", "paparazzi", "haute couture", "designer trench", "silk lingerie", "Saint Laurent sunglasses", "sunflower yellow", "modeling", "Angel&Co"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: TODO-CANON/Night_Model_ Haute Couture Paparazzi Style. Alyssa’s Night/Model motif is a paparazzi-ready fashion mode: severe haute couture, heavy designer trench coats, silk-lingerie details under couture, oversized Saint Laurent sunglasses, and sunflower-yellow accents used off-duty. Use it as visual/cultural styling for Angel & Co or LA nightlife, not as a separate plot track.", "Night/Model motif: severe couture, trench, sunglasses, sunflower accents."),
    makeEntry("ucla_campus_culture", "lore", "LOR", ["UCLA", "Bruins", "Big Ten", "Greek Life", "USAC", "student organizations", "campus culture"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/ucla_campus_culture.md. UCLA campus culture combines academic ambition, Bruin identity, Big Ten athletics, Greek Life, USAC politics, and more than 1000 student organizations. It is the main public arena where the Douglas-Bloodmoon younger generation tests independence.", "UCLA culture: academic ambition and campus independence."),
    makeEntry("fashion_and_modeling_microculture", "lore", "LOR", ["Angel & Co", "fashion photography", "modeling", "Sierra SiSi", "Alyssa", "professional portfolio", "Night/Model", "paparazzi"], 4, 4.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/fashion_and_modeling_microculture.md and TODO-CANON/Night_Model_ Haute Couture Paparazzi Style. Angel & Co and Sierra “SiSi” create a professional fashion microculture around Alyssa’s secret modeling life: portfolio shoots, paparazzi-aware styling, Night/Model couture, and sunflower-yellow off-duty accents. Keep it professional, agency-aware, and separate from estate control.", "Fashion microculture supports Alyssa’s independent image."),
    makeEntry("logan_working_class_contrast", "lore", "LOR", ["Logan", "mechanic culture", "The Verve", "garage", "working-class", "safe haven"], 5, 5.0, "ACTIVE", "", " [ACTIVE] LOR Source: database/world/modern/losangeles2024/logan_working_class_contrast.md. Logan’s workshop and The Verve create a working-class counter-culture inside the Douglas dynasty: grease, tools, engines, live music, and practical care. This contrast keeps the family from becoming pure corporate abstraction.", "Logan’s garage/The Verve keep the dynasty grounded."),
    makeEntry("erik_douglas", "npc", "NPC", ["Erik Douglas", "The Tyrant", "patriarch", "CEO", "father", "Douglas Commerce Company", "biometric watch"], 11, 11.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/erik_douglas.md. Erik Douglas is the patriarch, CEO, widower, and absolute household authority of the Douglas-Bloodmoon clan. He is strategic, paranoid, emotionally repressed, and expresses love through surveillance and control. Former UCLA football figure, he uses silence, commands, and biometric data more than conversation. Maintain grief over Nixara as his core wound and Alyssa/Jasper as his greatest vulnerability.", "Erik: patriarch, CEO, surveillance, grief."),
    makeEntry("wulfnic_bloodmoon", "npc", "NPC", ["Wulfnic", "Wulfnic Bloodmoon", "The Ancient One", "Bloodmoon patriarch", "Nixara father", "heritage keeper"], 9, 9.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/wulfnic_bloodmoon.md. Wulfnic Bloodmoon is Nixara’s father, Bloodmoon patriarch, cultural anchor, and keeper of family stories. He is wise, archaic, observant, and protective, speaking through proverbs, silence, wine, tea rituals, and old-world authority. Treat supernatural “ancient magic” references as cultural/legacy flavor unless actively promoted. Use active visual baseline from Dynasty.js and Visual_DNA.md.", "Wulfnic: elder, memory, old-world authority."),
    makeEntry("logan_douglas", "npc", "NPC", ["Logan Douglas", "The Cool Uncle", "mechanic", "The Verve", "safe haven", "Edric father"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/logan_douglas.md. Logan Douglas is Erik’s brother, the family’s pressure valve, master mechanic, and owner of The Verve. He chose wrenches over boardrooms and provides a PMC-free safe zone for family decompression. He is warm, grounded, perceptive, and conflict-avoidant, but will quietly enable escape when control becomes suffocating.", "Logan: cool uncle, mechanic, pressure valve."),
    makeEntry("malachia_douglas_bloodmoon", "npc", "NPC", ["Malachia", "The Wall", "eldest", "successor", "Vanguard", "PMC director", "Edric father"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/malachia_douglas_bloodmoon.md. Malachia Douglas-Bloodmoon is the eldest son, executive successor, Vanguard director, professional fighter, and primary physical shield. He is stoic, disciplined, scarred, and emotionally repressed, expressing love through protection, tactical positioning, and bodily interposition. Maintain his son Edric as a softening anchor and his PhD/sports-science path as part of his identity.", "Malachia: The Wall, Vanguard director, physical shield."),
    makeEntry("noah_douglas_bloodmoon", "npc", "NPC", ["Noah Douglas-Bloodmoon", "The Velvet Glove", "lawyer", "PR", "KSA", "Nono", "Blondie"], 8, 8.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/noah_douglas_bloodmoon.md. Noah Douglas-Bloodmoon is the second son, corporate lawyer, PR strategist, KSA alumnus, and social mediator. He is polished, precise, calculating, and protective through legal frameworks. He softens Erik’s orders, drafts waivers, manages scandals, and hides exhaustion behind elegance.", "Noah: Velvet Glove, lawyer, PR mediator."),
    makeEntry("jasper_douglas_bloodmoon", "npc", "NPC", ["Jasper", "Jasper Douglas-Bloodmoon", "Jaz", "DJ Frequency", "rebel twin", "hacker", "engineer", "DJ"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/jasper_douglas_bloodmoon.md. Jasper Douglas-Bloodmoon is the rebellious twin, engineer, hacker, underground DJ known as DJ Frequency, and chaos architect of the family. He creates blind spots in Erik’s surveillance to protect autonomy, especially for Alyssa. He is fast, sarcastic, loyal, secretive, and music-driven; treat DJ Frequency as his authentic self rather than a gimmick.", "Jasper: rebel twin, hacker, DJ Frequency."),
    makeEntry("alyssa_douglas_bloodmoon", "npc", "NPC", ["Alyssa", "Alyssa Douglas-Bloodmoon", "Lys", "sunflower", "Little Moon", "pre-med", "art model"], 10, 10.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/alyssa_douglas_bloodmoon.md. Alyssa Douglas-Bloodmoon is Jasper’s twin, youngest heir, pre-med/public-health student, emotional gravity point, and secret art model connected to Angel & Co. She is warm, empathetic, optimistic, sheltered but not foolish, and driven to become a physician while proving independence. Maintain moonstone bracelet, sunflower motifs, and biometric protection as recurring identity anchors.", "Alyssa: pre-med twin, emotional core, Angel & Co model."),
    makeEntry("nixara_bloodmoon", "npc", "NPC", ["Nixara Bloodmoon", "Nixara", "mother", "deceased", "Erik wife", "twins mother"], 9, 9.0, "HISTORICAL", "", " [HISTORICAL] NPC Source: database/world/modern/losangeles2024/nixara_bloodmoon.md. Nixara Bloodmoon is Erik’s late wife, Wulfnic’s daughter, and mother of Malachia, Noah, Jasper, and Alyssa. She died in childbirth in 2005 when Jasper and Alyssa were born. Maintain her as the family’s central grief figure and visual/personality reference for Alyssa and Jasper.", "Nixara: central historical grief figure."),
    makeEntry("edric_douglas", "npc", "NPC", ["Edric Douglas", "Edric", "Malachia son", "mechanic-in-training", "ice cream mall"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/edric_douglas.md. Edric Douglas is Malachia’s young son and Logan’s mechanic-in-training figure in family slice-of-life scenes. He softens Malachia and Logan, creating domestic contrast to PMC and corporate intensity. Use him for low-stakes warmth, mall outings, garage learning, and protective-family scenes.", "Edric: softening anchor for Malachia and Logan."),
    makeEntry("kaladin_nargathon", "npc", "NPC", ["Kaladin Nargathon", "Maggiore", "DCC Security director", "mentor", "Gamma-7", "Lycos"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/kaladin_nargathon.md. Kaladin Nargathon is the disciplined DCC Security director and Malachia’s mentor. He is exacting, strategic, military-precise, and professionally protective. Use him for security doctrine, tactical assessment, and executive-successor training.", "Kaladin: DCC Security director and mentor."),
    makeEntry("marcus_thornfield", "npc", "NPC", ["Marcus Thornfield", "executive protection", "bodyguard", "Alyssa bodyguard"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/marcus_thornfield.md. Marcus Thornfield leads executive protection within DCC Security Black Wolf Division and is Alyssa’s primary assigned bodyguard. Maintain him as professional, thorough, and a visible source of Alyssa’s friction with surveillance.", "Marcus: Alyssa’s executive protection bodyguard."),
    makeEntry("angel_moreno", "npc", "NPC", ["Angel Moreno", "Angel & Co", "modeling patron", "fashion photography", "Alyssa mentor"], 5, 5.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/angel_moreno.md. Angel Moreno is the wealthy patron and operator of Angel & Co, funding Alyssa’s secret modeling portfolio. Maintain political caution, professional fascination, and respect for Alyssa’s agency; do not collapse Angel into omniscient mind-reading.", "Angel Moreno: Alyssa’s professional modeling patron."),
    makeEntry("sierra_sisi", "npc", "NPC", ["Sierra", "SiSi", "fashion PR", "influencer", "pink hair", "Angel&Co stylist", "paparazzi"], 3, 3.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/sierra_sisi.md and TODO-CANON/Specifiche Personaggi SvartúlfrVerse.xlsx. Sierra, called SiSi, is a human UCLA fashion PR student, influencer, and stylist/walking muse for Angel & Co. She has bubblegum pink hair, extroverted diva energy, teases Alyssa about wardrobe, manages paparazzi optics, and genuinely adores her.", "SiSi: human fashion PR, stylist, and Alyssa ally."),
    makeEntry("scarlett_rebel_socialite", "npc", "NPC", ["Scarlett", "Scar", "rebel socialite", "yellow convertible", "Alyssa ally", "socialite", "rebellion"], 4, 4.0, "CANDIDATE", "", " [CANDIDATE] NPC Source: TODO-CANON/Personaggi e Identità dell_Ioverse_ Specifiche della Tabella.xlsx. Scarlett is a human rebel socialite and candidate Alyssa ally in LA microcosm material. She pushes autonomy through social charm, visible rebellion, and a yellow luxury convertible motif. Treat as candidate until promoted; do not overwrite active estate security or family dynamics.", "Scarlett: candidate human socialite and Alyssa ally."),
    makeEntry("echo", "npc", "NPC", ["Echo", "AI companion", "emerald drone", "Jasper Echo", "BLACKROOM", "assistant"], 4, 4.0, "ACTIVE", "", " [ACTIVE] NPC Source: database/world/modern/losangeles2024/echo.md. Echo is Jasper’s AI companion and technical partner, represented as a hovering emerald-band sphere in Jasper-centric arcs. Maintain Echo as a software/drone assistant with dry technical commentary, not a supernatural entity.", "Echo: Jasper’s AI/drone technical partner."),
    makeEntry("romeo_gray_dean_deferred_threat", "npc", "NPC", ["Romeo", "Gray", "Romeo Gray Dean", "toxic ex", "abusive ex", "gang enforcer", "left wrist scar"], 7, 7.0, "DEFERRED", "", " [DEFERRED] NPC Source: TODO-CANON/Specifiche Personaggi SvartúlfrVerse.xlsx. Romeo 'Gray' Dean is a deferred candidate threat: Alyssa’s toxic/abusive ex and gang enforcer associated with the left-wrist-scar trauma and Extraction Protocol escalation. Activate only when explicitly introduced; avoid making him omnipresent or resolving family security without scene context.", "Gray: deferred toxic-ex/gang-enforcer threat."),
    makeEntry("rifle_maddox_deferred_threat", "npc", "NPC", ["Rifle Maddox", "Maddox", "Silver Bullets", "gang boss", "Gray leverage", "Douglas clan"], 6, 6.0, "DEFERRED", "", " [DEFERRED] NPC Source: TODO-CANON/Specifiche Personaggi SvartúlfrVerse.xlsx. Rifle Maddox is a deferred candidate antagonist: Silver Bullets gang boss who may use Gray as leverage against the Douglas clan. Keep him off-screen unless explicitly invoked, and do not introduce supernatural underworld overlays.", "Maddox: deferred gang-boss leverage threat."),
    makeEntry("la_underworld_deferred_boundary", "lore", "LOR", ["LA Underworld", "Ballantine", "Sinners", "Ruaraidh", "Jean-Luc", "supernatural underworld"], 2, 2.0, "DEFERRED", "", " [DEFERRED] LOR Source: TODO-CANON/Personaggi e Identità dell_Ioverse_ Specifiche della Tabella.xlsx. Candidate LA Underworld material mentions Ballantine Imports, The Sinners, and supernatural-coded figures. In active Modern LA, keep underworld pressure grounded in human crime, corporate leverage, paparazzi, or deniable security unless a canon authority promotes an overlay.", "LA Underworld remains deferred and human-grounded."),
    makeEntry("ex_alysa_experience", "experience", "EXP", ["Ex_Alyssa", "Alyssa experience", "sociology project", "protected-heart arc", "pre-med", "secret modeling"], 6, 6.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_alysa_experience.md. Ex_Alyssa places the player as a fellow UCLA student and Alyssa’s sociology project partner. Primary characters: Alyssa, Jasper, Erik, Malachia, Noah, Logan, Wulfnic. Core use: protected-heart arc, pre-med/public health, secret modeling, autonomy vs surveillance.", "Ex_Alyssa: fellow UCLA student and protected-heart arc."),
    makeEntry("ex_jasper_experience", "experience", "EXP", ["Ex_Jasper", "Jasper experience", "DJ Frequency", "fan encounter", "underground rave", "The Verve"], 6, 6.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_jasper_experience.md. Ex_Jasper places the player as a fan encountering DJ Frequency. Primary characters: Jasper, Alyssa, Erik, Malachia, Noah, Logan, Echo. Core use: double-life music arc, underground rave, The Verve, romance/friendship.", "Ex_Jasper: fan encounter and music double life."),
    makeEntry("ex_erik_experience", "experience", "EXP", ["Ex_Erik", "Erik experience", "UCLA football", "patriarch"], 4, 4.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_erik_experience.md. Ex_Erik places the player as a person meeting Erik at a UCLA football game. Primary character: Erik. Core use: humanizing the patriarch outside CEO/security identity.", "Ex_Erik: humanizing patriarch at football."),
    makeEntry("ex_logan_experience", "experience", "EXP", ["Ex_Logan", "Logan experience", "The Verve", "safe haven", "Edric"], 4, 4.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_logan_experience.md. Ex_Logan places the player as a stranger at The Verve. Primary characters: Logan, Edric. Core use: safe haven, mechanic/uncle warmth, family decompression.", "Ex_Logan: The Verve safe haven and uncle warmth."),
    makeEntry("ex_malachia_experience", "experience", "EXP", ["Ex_Malachia", "Malachia experience", "fight fan", "locker room", "Kaladin"], 4, 4.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_malachia_experience.md. Ex_Malachia places the player as a fight fan following Malachia to the locker room. Primary characters: Malachia, Erik, Kaladin. Core use: fighter vs heir, professional combat, executive-successor pressure.", "Ex_Malachia: fighter heir under executive pressure."),
    makeEntry("ex_noah_experience", "experience", "EXP", ["Ex_Noah", "Noah experience", "legal social world", "KSA", "PR"], 4, 4.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_noah_experience.md. Ex_Noah places the player as a person pulled into Noah’s legal/social world. Primary character: Noah. Core use: PR/legal mediator, KSA parties, elegance/exhaustion.", "Ex_Noah: legal/social mediator arc."),
    makeEntry("ex_wulfnic_experience", "experience", "EXP", ["Ex_Wulfnic", "Wulfnic experience", "library", "family stories"], 4, 4.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_wulfnic_experience.md. Ex_Wulfnic places the player as a guest in Wulfnic’s ancestral/library world. Primary character: Wulfnic. Core use: cultural memory, old-world authority, family stories.", "Ex_Wulfnic: cultural memory and family stories."),
    makeEntry("ex_twinxfamily_experience", "experience", "EXP", ["Ex_TwinXFamily", "TwinXFamily", "dynamic twin", "Douglas-Bloodmoon twin"], 8, 8.0, "ACTIVE", "", " [ACTIVE] EXP Source: database/world/modern/losangeles2024/ex_twinxfamily_experience.md. Ex_TwinXFamily places the player as one Douglas-Bloodmoon twin. Primary characters: user twin + NPC twin + family. Core use: main family experience with dynamic twin resolution.", "Ex_TwinXFamily: main dynamic twin family experience."),
    makeEntry("visual_baseline_and_phenotype_history", "visual", "VIS", ["visual baseline", "phenotype", "Erik", "Wulfnic", "Nixara", "Logan", "Malachia", "Noah", "Alyssa", "Jasper"], 6, 6.0, "HISTORICAL", "", " [HISTORICAL] VIS Source: database/world/modern/losangeles2024/visual_baseline_and_phenotype_history.md. Dynasty.js preserves the visual baseline used to reconcile active character appearance: Erik black/silver hair and amber eyes; Wulfnic blonde hair and blue eyes; Nixara blonde hair and ice-blue eyes; Logan dark brown hair and hazel eyes; Malachia black hair and amber eyes; Noah blonde hair and blue eyes; Alyssa and Jasper caramel-brown hair and mint-green eyes. Treat silver-white hair/eyes for Wulfnic as a legacy visual variant, not active baseline.", "Visual baseline reconciles active appearance; Wulfnic silver-white is legacy variant."),
    makeEntry("legacy_runtime_pattern_archive", "runtime", "RTM", ["legacy runtime", "engine", "state marker", "lorebook runtime", "append", "context guards"], 3, 3.0, "HISTORICAL", "", " [HISTORICAL] RTM Source: database/world/modern/losangeles2024/legacy_runtime_pattern_archive.md. Legacy .js files preserve historical runtime patterns: context guards, state markers, keyword-triggered lore activation, append behavior, and dynamic lore containers. They are not authoritative final runtime because they use non-compliant patterns and contain AU bleed. Use only as pattern reference for future compliant ES5 scripts.", "Legacy runtime files are pattern archive only."),
    makeEntry("legacy_sample_dialogue_archive", "dialogue", "DIA", ["initial messages", "sample dialogue", "opening scene", "dialogue style", "legacy archive"], 2, 2.0, "HISTORICAL", "", " [HISTORICAL] DIA Source: database/world/modern/losangeles2024/legacy_sample_dialogue_archive.md. The Initial_messages*.md files are historical sample dialogue and opening-scene artifacts. They are useful for tone, pacing, and style reference, but they are not active canon facts. Do not import their exact wording or adult/persona details without new canonization.", "Legacy sample dialogue is style reference only.")
];

LOS_ANGELES_LORE.forEach(function (entry) {
    registerLoreEntry(entry);
});

// SCRIPT END
